TAP for TUF developer key management
theupdateframework/taps pull request #141
Opened 2021-07-27 15:23 UTC by mnm678

This TAP proposes the use of Fulcio to improve developer key management in TUF.

2021-08-12 18:33 UTC, mnm678 commented
cc @JustinCappos

2021-08-12 19:09 UTC, trishankatdatadog commented
As I've mentioned before:

One thing I don't see is how to _bind_ the specific, ephemeral developer public key to a specific version of the message (i.e., TUF targets metadata). Recording it on Rekor is one way, but the TUF client may not always be able to efficiently verify that, especially in offline environments. Perhaps the message could _also_ record the ephemeral pubkey itself, but it's something to think about.

Basically, how do I know which keys were used to sign which messages, even if all the keys are vouched by the Fulcio root?

2021-08-12 19:14 UTC, mnm678 commented
> Basically, how do I know which keys were used to sign which messages, even if all the keys are vouched by the Fulcio root?

The Fulcio certificate chain would be included in the signature. But yes, the client would need to make sure that this particular certificate is allowed to sign the metadata either by checking the TL directly, or by trusting the repo to do so. May be the repo could additionally indicate the correct certificate?

2021-08-18 07:58 UTC, axelsimon commented
Rendered version [here](https://github.com/mnm678/taps/blob/fulcio-tap/candidate-fulcio-tap.md), for those interested.

2021-08-18 08:19 UTC, axelsimon reviewed
Just a few more comments / suggestions on this. Thanks for turning it into a TAP @mnm678!

2021-08-18 08:19 UTC, axelsimon commented on candidate-fulcio-tap.md
> +* Title: Fulcio for TUF developer key management
I have a feeling we want to make the title a bit more explanatory, as "Fulcio" is not (yet) a household name.
Maybe something like "Ephemereal identity verification using Sigstore Fulcio for TUF developer key management". That's long and clunky, but gives an idea.

2021-08-18 08:19 UTC, axelsimon commented on candidate-fulcio-tap.md
> +In order to achieve end-to-end software update security, TUF requires developers to sign updates with a private key. However, this has proven challenging for some implementers as developers then have
```suggestion
In order to achieve end-to-end software update security, TUF requires developers to sign updates with a private key. However, this has proven challenging for some implementers as developers then have to create, store, and secure these private keys in order to ensure they remain private. This TAP proposes using Sigstore’s Fulcio project to simplify developer key management by allowing developers to use existing accounts to verify their identity when signing updates. A TUF targets roles may delegate to Fulcio identities instead of private keys, and these identities, and the corresponding certificates can be used for verification.
```

2021-08-18 08:19 UTC, axelsimon commented on candidate-fulcio-tap.md
> +Protecting a private key from loss or compromise is no simple matter. [Several](https://blog.npmjs.org/post/185397814280/plot-to-steal-cryptocurrency-foiled-by-the-npm) [attacks](https://jsoverson.me
```suggestion
Protecting a private key from loss or compromise is no simple matter. [Several](https://blog.npmjs.org/post/185397814280/plot-to-steal-cryptocurrency-foiled-by-the-npm) [attacks](https://jsoverson.medium.com/how-two-malicious-npm-packages-targeted-sabotaged-one-other-fed7199099c8) on software update systems have been achieved through the use of a compromised key, as securing private keys can be challenging, and sometimes expensive (using hardware keys such Yubikeys etc)., especially over a period of time.
```

2021-08-18 08:19 UTC, axelsimon commented on candidate-fulcio-tap.md
> +In a previous draft of [PEP 480](https://www.python.org/dev/peps/pep-0480/), the authors proposed using [MiniLock](https://www.minilock.io) - a tool which derives ed25519 keys from a user-chosen pass
```suggestion
In a previous draft of [PEP 480](https://www.python.org/dev/peps/pep-0480/), the authors proposed using [MiniLock](https://www.minilock.io) – a tool which derives ed25519 keys from a user-chosen passphrase –  to simplify developer key management. However, this requires developers to remember a new and additional passphrase for use when uploading packages. Furthermore, the MiniLock project is [no longer maintained](https://github.com/kaepora/miniLock).
```
En-dash for consistency with previous paragraph. Link on Minilock to let the user see for themselves what we are saying.

2021-08-18 08:19 UTC, axelsimon commented on candidate-fulcio-tap.md
> +In this TAP, we instead propose use of the Sigstore project. Sigstore has a growing number of adoptions, and provides a simple mechanism for developers to verify their identity using short-lived keys
```suggestion
In this TAP, we instead propose use of the sigstore project. Sigstore has a growing number of adoptions, and provides a simple mechanism for developers to verify their identity using short-lived keys and ad-hoc certificates issued on the basis of OIDC. Sigstore provides two services, [Fulcio](https://github.com/sigstore/fulcio) (a WebPKI) and [Rekor](https://github.com/sigstore/rekor) (a transparency log). With sigstore, short-lived keys do not need to be secured as they are only valid for a small window of time. Fulcio certificates and client generated signatures are published to a timestamped transparency log managed by Rekor so that verifiers can ensure that the certificates were valid at the time of the signature.
```

2021-08-19 18:50 UTC, mnm678 commented
Thanks for the review @axelsimon! I updated the document

2021-08-31 13:29 UTC, axelsimon reviewed
A few more comments.

2021-08-31 13:29 UTC, axelsimon commented on candidate-fulcio-tap.md
> +In this TAP, we instead propose use of the sigstore project. Sigstore has a growing number of adoptions, and provides a simple mechanism for developers to verify their identity using short-lived keys
```suggestion
In this TAP, we instead propose use of the sigstore project. Sigstore has a growing number of adoptions, and provides a simple mechanism for developers to verify their identity using short-lived keys and ad-hoc certificates issued on the basis of OIDC. Sigstore provides two services, [Fulcio](https://github.com/sigstore/fulcio) (a WebPKI) and [Rekor](https://github.com/sigstore/rekor) (a transparency log). With sigstore, long-term efforts to keep private keys secure are not necessary, as short-lived keys are only valid for a small window of time. Fulcio certificates and client generated signatures are published to a timestamped transparency log managed by Rekor so that verifiers can ensure that the certificates were valid at the time of the signature.
```

2021-08-31 13:29 UTC, axelsimon commented on candidate-fulcio-tap.md
> +    “email”: EMAIL,
Dan mentions in his blog post [Using The Update Framework in Sigstore](https://dlorenc.medium.com/using-the-update-framework-in-sigstore-dc393cfe6b52) "email or SPIFFE-based" when mentioning the OIDC identities that can be used with Fulcio. Should this TAP be amended to reflect that? Are SPIFFE-based IDs something we want to consider in the context of this TAP?

2021-08-31 13:29 UTC, axelsimon commented on candidate-fulcio-tap.md
> +Where SERVER is the Fulcio server used to generate the certificate, EMAIL is the identity of the party who is authorized to sign, and ISSUER is the OIDC entity used by Fulcio for verification. The cl
```suggestion
Where SERVER is the Fulcio server used to generate the certificate, EMAIL is the identity of the party who is authorized to sign, and ISSUER is the OIDC entity used by Fulcio for verification. The client MUST establish trust in the Fulcio server using a trusted channel before using it for verification (see Verification).
```

2021-08-31 13:29 UTC, axelsimon commented on candidate-fulcio-tap.md
> +Using this mechanism, the developer requests a certificate from Fulcio, verifies their identity using OIDC, uses the certificate to sign their targets metadata, and uploads the signed metadata. This
```suggestion
Using this mechanism, the developer requests a certificate from Fulcio, verifies their identity using OIDC, uses the certificate to sign their targets metadata, and uploads the signed metadata. This signature, and the associated Rekor timestamp obtained by querying the Rekor server, MUST be verified by the repository and MAY be verified by the end user by verifying the certificate through Fulcio and the timestamp through Rekor. The verifier MUST obtain the Fulcio root key using a secure offline method prior to verifying the signature and associated certificate.
```

May be worth being specific here.

2021-08-31 13:29 UTC, axelsimon commented on candidate-fulcio-tap.md
> +Most of these steps SHOULD be done automatically using a tool, to simplify operations for developers.
```suggestion
Most of these steps SHOULD be done automatically using a tool, to simplify operations for developers and minimise the risk of human errors.
```

2021-08-31 13:29 UTC, axelsimon commented on candidate-fulcio-tap.md
> +Developers should monitor the TL for certificates associated with their OIDC accounts to look for unauthorized activity. If they see a certificate on the TL that they did not issue, the developer sho
```suggestion
Developers should monitor the transparency log (TL) for certificates associated with their OIDC accounts to look for unauthorized activity. If they see a certificate on the TL that they did not issue, the developer should replace any compromised metadata, and report the compromise to the maintainers of the Fulcio server and any targets metadata owners who delegate to the compromised account.
```

2021-08-31 13:29 UTC, axelsimon commented on candidate-fulcio-tap.md
> +If only the transparency log is compromised, the attacker will not be able to do anything without cooperation from the Fulcio server. However, if the attacker compromises both the Fulcio server and t
This might be a nitpick, or just show my lack of understanding, but would it be more precise to say that it is the **trust in the** Fulcio server and transparency log that could be recovered? I expect the servers would need to be scrapped and reinstalled and data restored from a last known good backup. Is this correct?

2021-08-31 13:29 UTC, axelsimon commented on candidate-fulcio-tap.md
> +TODO
@mnm678 Is this a blocker for merging? :)

2021-08-31 18:57 UTC, mnm678 commented on candidate-fulcio-tap.md
> +    “email”: EMAIL,
For simplicity, I'd rather not mention SPIFFE directly in the TUF spec, but I can change this to something more generic like 'OIDC identity' with email used as an example, so that implementations that also use SPIFFE can use this field, without us having to define that here.

2021-08-31 19:05 UTC, mnm678 commented on candidate-fulcio-tap.md
> +If only the transparency log is compromised, the attacker will not be able to do anything without cooperation from the Fulcio server. However, if the attacker compromises both the Fulcio server and t
Using Sigstore's TUF root keys, we can replace the Fulcio or Rekor signing keys. The transparency log may need to be scrapped if malicious content was added, but Fulcio should be able to recover without scrapping the server.

cc @trishankatdatadog @asraa

2021-08-31 19:07 UTC, mnm678 commented on candidate-fulcio-tap.md
> +TODO
No, we'll need this before the TAP moves from draft to accepted, but it shouldn't be a blocker for merging the draft. And I think @asraa has some initial work in go-tuf that I can link here anyway.

2021-09-01 17:40 UTC, axelsimon commented on candidate-fulcio-tap.md
> +TODO
Ok, nice to hear! Thanks @mnm678.

2021-09-01 17:41 UTC, axelsimon commented on candidate-fulcio-tap.md
> +    “email”: EMAIL,
I see your point, mentioning SPIFFE would likely complicate things for no good reason. Thanks for the change.

2021-09-01 17:46 UTC, axelsimon commented on candidate-fulcio-tap.md
> +If only the transparency log is compromised, the attacker will not be able to do anything without cooperation from the Fulcio server. However, if the attacker compromises both the Fulcio server and t
I guess what's driving my thought is this idea that once a server has been compromised, you just can't be sure you've recovered it  cleaned it up fully and you should just redeploy it. But given Fulcio and Rekor are cloud-native, that way of thinking is a bit moot: the Fulcio and Rekor containers are just redeployed on a regular basis anyway, and then it's just a question of trusting the data. So yeah, maybe an issue for Rekor, but less one for Fulcio. Maybe it's the wording "server" that still makes me think following the non cloud-native paradigm.Thanks!

2021-09-09 13:56 UTC, mnm678 commented
@trishankatdatadog @joshuagl Any blockers on having this merged in as a draft?

2021-09-09 14:45 UTC, joshuagl approved these changes
This looks like a good basis to merge as draft. Do we want to make an explicit recommendation (in security analysis?) that systems using Fulcio for developer key management SHOULD set up an auditor?

2021-09-10 15:29 UTC, erickt commented on candidate-fulcio-tap.md
> +In this TAP, we instead propose use of the sigstore project. Sigstore has a growing number of adoptions, and provides a simple mechanism for developers to verify their identity using short-lived keys
By using OIDC, does this mean we need to communicate with the server in order to verify they’re properly signed? That seems fine for certain use cases, but I believe this means we can’t use this key type for a client metadata backstop if we land #128.

2021-09-10 16:42 UTC, mnm678 commented on candidate-fulcio-tap.md
> +In this TAP, we instead propose use of the sigstore project. Sigstore has a growing number of adoptions, and provides a simple mechanism for developers to verify their identity using short-lived keys
Yes, that is one of the tradeoffs of this TAP. The cert can be verified to a defined Fulcio server locally (described in the verification section), but the transparency log checks require internet access.

2021-09-10 16:44 UTC, mnm678 commented
> This looks like a good basis to merge as draft. Do we want to make an explicit recommendation (in security analysis?) that systems using Fulcio for developer key management SHOULD set up an auditor?

Added

2021-09-10 16:59 UTC, trishankatdatadog commented on candidate-fulcio-tap.md
> +In addition to developer monitoring, the TL should have auditors that watch the log for any suspicious activity. If something bad is found in the TL, then auditors must indicate this to clients to en
Should make clear you mean threshold signatures involving both developers and auditors. This requires [multi-role delegations](https://github.com/theupdateframework/taps/blob/master/tap3.md).

2021-09-10 16:59 UTC, trishankatdatadog commented on candidate-fulcio-tap.md
> +# Security Analysis
Missing what a developer does when the developer is compromised, and an "authentic" but unauthorized signature is issued.

2021-09-10 16:59 UTC, trishankatdatadog commented on candidate-fulcio-tap.md
> +Where CERTIFICATE is a Fulcio signing certificate in PEM format. CERTIFICATE MUST be uploaded to a timestamped transparency log upon creation.
Does the CERTIFICATE include the timestamped signature? Not clear from here.

2021-09-10 17:39 UTC, mnm678 commented on candidate-fulcio-tap.md
> +Where CERTIFICATE is a Fulcio signing certificate in PEM format. CERTIFICATE MUST be uploaded to a timestamped transparency log upon creation.
it's an x509 cert, so it is signed and has a `notbefore` and `notAfter`. I can't find any Fulcio specific documentation, other than [the code](https://github.com/sigstore/fulcio/blob/b37c46c767e60714a13b8bddee0e00522a7a10a2/pkg/ca/fulcioca/fulcioca.go#L31)

2021-11-29 16:41 UTC, mnm678 commented
@trishankatdatadog @erickt I made edits and responded inline. Any objections to merging as a draft?

2021-11-29 16:43 UTC, axelsimon reviewed
A few more suggestions, trying to resolve open conversations / comments.

2021-11-29 16:43 UTC, axelsimon commented on candidate-fulcio-tap.md
> +Developers should monitor the transparency log (TL) for certificates associated with their OIDC accounts to look for unauthorized activity. If they see a certificate on the TL that they did not issue
Do we want a SHOULD here ("Developers SHOULD monitor the transparency log") or is this a softer suggestion?

2021-11-29 16:43 UTC, axelsimon commented on candidate-fulcio-tap.md
> +In addition to developer monitoring, the TL should have auditors that watch the log for any suspicious activity. If something bad is found in the TL, then auditors must indicate this to clients to en
Same question here, "then auditors MUST indicate this to clients"?

```suggestion
In addition to developer monitoring, the TL should have auditors that watch the log for any suspicious activity. If something bad is found in the TL, then auditors must indicate this to clients to ensure they don’t use bad certificates. Clients SHOULD have a way to ensure that the transparency log has been audited. For example, auditors may upload signed targets metadata to the repository upon valid completion of an audit. Clients can look for the auditor signature on targets metadata, in addition to the developer signature, before verifying any Fulcio-signed delegated targets. In practice, this means using threshold signature of both developers and auditors, which in turn requires [multi-role delegations](https://github.com/theupdateframework/taps/blob/master/tap3.md). The auditor MUST only sign metadata if all signatures in the TL look good. If the auditor detects a problem, they MAY revoke the auditor-signed metadata.
```

An attempt at incorporating the points @trishankatdatadog was making.

2021-11-29 16:43 UTC, axelsimon commented on candidate-fulcio-tap.md
> +If the bad certificates are due to a compromised Fulcio server, the Fulcio server SHOULD be revoked using the root of trust.
Maybe nitpicking, but why SHOULD and not MUST here?

2021-11-29 16:43 UTC, axelsimon commented on candidate-fulcio-tap.md
> +This TAP improves security by eliminating the risk of developers losing their keys if they chose to use Fulcio instead of a traditional public key cryptosystem. However, it adds 2 additional services
```suggestion
This TAP improves security by eliminating the risk of developers losing their keys if they chose to use Fulcio instead of a traditional public key cryptosystem. However, it adds 2 additional services that may be compromised: the Fulcio server and the Rekor transparency log. In this section, we will analyze the impact and recovery in each of these cases.
```

2021-11-29 16:43 UTC, axelsimon commented on candidate-fulcio-tap.md
> +If the Fulcio server is compromised, it may issue certificates on behalf of any developer who uses Fulcio to verify their identity. However, the Fulcio server is backed by offline keys that are signe
```suggestion
If the Fulcio server is compromised, it may issue certificates on behalf of any attacker who uses Fulcio to verify their identity. However, the Fulcio server is backed by offline keys that are signed by TUF root keys, and so it is possible to recover from any Fulcio server compromise. Additionally, all Fulcio certificates are published to a transparency log, so auditors will notice if the Fulcio server is misbehaving and indicate this to users, for example through the use of [multi-role delegations](https://github.com/theupdateframework/taps/blob/master/tap3.md) to a threshold of both auditor-signed metadata and developer-signed metadata.
```
Let's state clearly that "any developer" in this case really means an attacker, do you agree @mnm678?

2021-11-29 16:43 UTC, axelsimon commented on candidate-fulcio-tap.md
> +# Security Analysis
I think this is now covered by the section L93 ("If a developer's OIDC credentials are compromised, the developer should use existing TUF processes for revocation").

2021-11-29 16:55 UTC, mnm678 commented on candidate-fulcio-tap.md
> +In this TAP, we instead propose use of the sigstore project. Sigstore has a growing number of adoptions, and provides a simple mechanism for developers to verify their identity using short-lived keys
The downside would be that any updates (especially revocations) would be missing from the local copy. This could certainly be a good workaround for some use cases though.

2021-11-29 16:56 UTC, mnm678 commented on candidate-fulcio-tap.md
> +# Security Analysis
yes, I added that line, but didn't resolve this conversation. I'll do so now unless @trishankatdatadog objects.

2021-11-29 17:01 UTC, mnm678 commented on candidate-fulcio-tap.md
> +Developers should monitor the transparency log (TL) for certificates associated with their OIDC accounts to look for unauthorized activity. If they see a certificate on the TL that they did not issue
Good catch, I updated this here and elsewhere in the TAP.

2021-11-30 15:08 UTC, axelsimon commented on candidate-fulcio-tap.md
> +In this TAP, we instead propose use of the sigstore project. Sigstore has a growing number of adoptions, and provides a simple mechanism for developers to verify their identity using short-lived keys
Turns out, there's a better answer, from the recently published [Busting 5 Sigstore Myths](https://chainguard.dev/posts/2021-11-19-sigstore-myths):
> #### Myth #4: The transparency log means you can’t verify signatures offline.
> We use what’s called "stapled inclusion proofs” by default, meaning you can verify an object is present in the transparency log without needing to contact the transparency log! The signer is responsible for gathering this evidence from the log and presenting it alongside the artifact and signature. We store this in an OCI image automatically, but you can treat it like a normal file and copy it around for verification as well.

2021-11-30 15:12 UTC, axelsimon commented on candidate-fulcio-tap.md
> +In addition, the repository MUST, and clients SHOULD additionally query the transparency log to ensure that the Fulcio certificate is valid at the time that it was used.
```suggestion
In addition, the repository MUST, and clients SHOULD additionally query the transparency log to ensure that the Fulcio certificate is valid at the time that it was used. This may be done by directly querying the transparency log or, in cases where online verification is not possible, via the use of stapled inclusion proofs, evidence gathered by the signer from the log and presented alongside the software and signature.
```

2021-11-30 16:15 UTC, mnm678 commented on candidate-fulcio-tap.md
> +In this TAP, we instead propose use of the sigstore project. Sigstore has a growing number of adoptions, and provides a simple mechanism for developers to verify their identity using short-lived keys
Thanks @axelsimon for adding this to the text below.

2022-01-10 20:15 UTC, mnm678 commented
The previous reviews were dismissed by some recent changes. @joshuagl @trishankatdatadog @axelsimon can I get 2 reviews/approvals for this to be merged as draft?

2022-03-14 21:08 UTC, trishankatdatadog commented
Ooops, are we blocking here? What do you need from me?

2022-03-16 08:32 UTC, trishankatdatadog commented
> Can you review/approve for this to be merged as a draft?

I'm ok to approve this as a draft so long as we add concrete details on exactly how the SigStore RFC 3161 timestamping can be verified either online or offline by a TUF client.

2022-03-16 15:45 UTC, haydentherapper commented on candidate-fulcio-tap.md
> +In addition, the repository MUST, and clients SHOULD additionally query the transparency log to ensure that the Fulcio certificate is valid at the time that it was used. This may be done by directly
Should you also need to mention an out of band process is needed distribute the verification material for verifying an offline proof?

2022-03-16 15:45 UTC, haydentherapper commented on candidate-fulcio-tap.md
> +Developers SHOULD monitor the transparency log (TL) for certificates associated with their OIDC accounts to look for unauthorized activity. If they see a certificate on the TL that they did not issue
I’m not sure what benefit there is to reporting this to Fulcio maintainers. There is currently no support for redaction of the CT log, and nothing to delete since certificates aren’t persisted.

2022-03-16 16:09 UTC, trishankatdatadog commented on candidate-fulcio-tap.md
> +Developers SHOULD monitor the transparency log (TL) for certificates associated with their OIDC accounts to look for unauthorized activity. If they see a certificate on the TL that they did not issue
Good point. Maybe we should think about adding ways for clients to discover compromised Fulcio keys (and corresponding compromised TUF targets signed by those keys).

2022-03-16 20:18 UTC, haydentherapper commented on candidate-fulcio-tap.md
> +Developers SHOULD monitor the transparency log (TL) for certificates associated with their OIDC accounts to look for unauthorized activity. If they see a certificate on the TL that they did not issue
Would we want this to be managed, either by Fulcio, an ecosystem, or an individual developer? For the first two, there's a question of authentication. For the latter, there's a question for discovery.

2022-03-16 20:23 UTC, trishankatdatadog commented on candidate-fulcio-tap.md
> +Developers SHOULD monitor the transparency log (TL) for certificates associated with their OIDC accounts to look for unauthorized activity. If they see a certificate on the TL that they did not issue
I have no idea yet. I feel like it's an important practical issue all Fulcio users must eventually deal with.

2022-03-22 17:03 UTC, mnm678 commented on candidate-fulcio-tap.md
> +Developers SHOULD monitor the transparency log (TL) for certificates associated with their OIDC accounts to look for unauthorized activity. If they see a certificate on the TL that they did not issue
Good point. I removed this and clarified that replacing the signature will make a new valid Fulcio cert

2022-03-22 17:04 UTC, mnm678 commented
> I'm ok to approve this as a draft so long as we add concrete details on exactly how the SigStore RFC 3161 timestamping can be verified either online or offline by a TUF client.

I added a bit of clarification, plus a link to the Fulcio docs. Does that work?

2022-03-22 17:11 UTC, trishankatdatadog commented
> I added a bit of clarification, plus a link to the Fulcio docs. Does that work?

Not really. Sorry to be a bit painful, but this TAP expects the reader to fully grok Fulcio/Rekor/RFC 3161 with very little background material. Would you mind detailing an example of this stapled proof, and show us how to verify the RFC 3161 timestamp at the time? I'm fairly sure everyone else has thought this through, but I haven't, and I want to make sure we don't accidentally miss anything.

2022-03-28 13:50 UTC, jku commented
So I've had another go at implementing this (so far in my head only, sorry), and have some new comments. I don't want to prevent this being merged but leaving the notes here...

### Source of trust

We should not refer to root certificates with URLs as I think I originally suggested and as Marina has done here. That is a reasonable for clients who don't have other choices... but for TUF there seems to be an obvious choice: include the complete root (or intermediate) certificate in the delegating metadata. The simplest option is to include the root certificate instead of the URL in each key definition (but it's also clear that many keys are likely to share the same root certificate so...).

Including the root certificate with the key means two things:
* root certificate that changes can be updated with the usual TUF mechanisms
* it's now clear what the source of trust is: a malicious fulcio CA could still give out untrusted certificates but now TUF metadata can put a stop to it at any time


### Focus on keys & signatures

I think the TAP should focus on the core TUF functionality and how to integrate fulcio certificates in it. Rekor, transparency logging and auditing should be clearly marked as add-ons: I don't think any of that should be required for a TUF+Fulcio integration. 

In other words I don't agree that 
* _clients SHOULD query Rekor to validate certificate validity_: why is this critical? what is the attack?
* _repository MUST query Rekor to validate certificate validity_: repository can just require that certificate is still valid at upload time, why would it ask or trust rekor for this?
* _Developers SHOULD monitor Rekor for "unauthorized activity"_. This feels like something I won't actually do and neither will anyone else -- should we put in a spec without defining what it means?
* _Rekor SHOULD have auditors that watch the log for any "suspicious activity"_: this is even more vague. Great if someone comes up with a way to do it but I don't think this belongs in the spec until there's something _specific_ about how this is done
* _Clients SHOULD have a way to ensure that the transparency log has been audited_: Again so vague that it does not belong in a spec

This sounds like I'm complaining but it's more that I think there are several documents in this one document: One that describes the core "TUF with short lived signing certificates" and others that describe that add-on functionality that may be enabled in the future by the first one.

2022-03-30 20:45 UTC, mnm678 commented
> ### Source of trust
> 
> We should not refer to root certificates with URLs as I think I originally suggested and as Marina has done here. That is a reasonable choice for clients who don't have other choices... but for TUF there seems to be an obvious choice: include the complete root (or intermediate) certificate in the delegating metadata. The simplest option is to include the root certificate instead of the URL in each key definition (but it's also clear that many keys are likely to share the same root certificate so...).
> 

I agree. Including the certificate info in the delegating metadata does seem more TUF-like, and I'll update the document accordingly.

> ### Focus on keys & signatures
> 
> I think the TAP should focus on the core TUF functionality and how to integrate fulcio certificates in it. Rekor, transparency logging and auditing should be clearly marked as add-ons: I don't think any of that should be required for a TUF+Fulcio integration.
> 

The user needs to be able to validate that the short-lived keys from Fulcio were valid at the time the metadata was signed. TUF's existing timeliness properties allow for expiration, but not verification of when something was signed. To get this, we need an RFC 3161 timestamping service (or similar). The Rekor TL gives us these timestamps, as well as the auditability properties. However, this could be required in a more generic way than what is described here (ie, we could use a stapled inclusion proof from any RFC 3161 service, not just Rekor).

2022-03-30 21:19 UTC, trishankatdatadog commented on candidate-fulcio-tap.md
> +In addition, the repository MUST, and clients SHOULD additionally query the Rekor transparency log to ensure that the Fulcio certificate is valid at the time that it was used. To do the user can dire
```suggestion
In addition, the repository MUST, and clients SHOULD additionally query the Rekor transparency log to ensure that the Fulcio certificate is valid at the time that it was used. To do the user can directly query the transparency log for the Fulcio certificate. They can then verify that the certificate was uploaded to the Rekor, and use the timestamp in Rekor to verify that the key was valid at the time it was used to sign TUF metadata.
```

2022-03-30 21:19 UTC, trishankatdatadog commented on candidate-fulcio-tap.md
> +In cases where online verification is not possible, stapled inclusion proofs, evidence gathered by the signer from the log, may be presented alongside the software and signature. The user may use the
```suggestion
In cases where online verification is not possible, stapled inclusion proofs (i.e., evidence gathered by the signer from the log) MAY be presented alongside the software and signature. The user MAY use these proofs instead of directly querying Rekor's transparecy log. Verification material for these stapled inclusion proofs MUST be distributed out of band alongside the Rekor root. Documentation about querying Rekor is available [here](https://docs.sigstore.dev/rekor/CLI).
```

2022-03-31 06:52 UTC, jku commented
> The user needs to be able to validate that the short-lived keys from Fulcio were valid at the time the metadata was signed.

I agree that would be good and reasonable _as an option_ but I am not convinced the benefits outweigh the cost for the minimal implementation: you are saying the client now MUST be able to interact with rekor in addition to dealing with TUF. This adds even more implementation complexity to TUF client that IMO really does not need any more complexity.

Assuming the repository is required to check the certificate validity at upload time, a successful attack would require both:
* compromise of the short lived private key (so attacker can use the key after or before the certificate is valid) and
* compromise of repository (so repository does not check the certificate validity time as it's supposed to)

That is a risk but it does not seem like an unreasonable one. Or am I missing something in the scenario?

2022-03-31 07:12 UTC, jku commented
> you are saying the client now MUST be able to interact with rekor

Actually I think this is a "SHOULD" in the text, sorry about that. Even then, I think we should promote the non-rekor implementation as clearly supported if it seems to be to secure enough for our purposes.

Adding Rekor lookups to the signature verification path is something I really don't want to do unless it's absolutely necessary.

2022-03-31 14:46 UTC, mnm678 commented
Oh, so you're suggesting that we remove the Rekor requirement for the *client*, but leave this requirement for the *repository*? In that case I think I agree. It's currently listed as a SHOULD for client Rekor verification, but I can downgrade that to a MAY for especially paranoid clients. If clients opt for stapled inclusion proofs the client verification doesn't require an extra lookup, but I agree that the added security may not be worth the hassle even in that case.

2022-04-01 06:37 UTC, jku commented
> Oh, so you're suggesting that we remove the Rekor requirement for the client, but leave this requirement for the repository? 

The client part is what I'm focusing on yes, and I consider that the important point... but I'm also not sure if rekor is required for the repository: When a new signing cert signature is submitted to the repository, the repository could just require that the signing cert **must be valid at submission time**. So there's no need to use rekor to check if signature was valid a few seconds ago because repository already knows for sure that the signing cert is currently valid.

2022-04-28 19:10 UTC, mnm678 commented
> The client part is what I'm focusing on yes, and I consider that the important point... but I'm also not sure if rekor is required for the repository: When a new signing cert signature is submitted to the repository, the repository could just require that the signing cert **must be valid at submission time**. So there's no need to use rekor to check if signature was valid a few seconds ago because repository already knows for sure that the signing cert is currently valid.

I switched the client to a may. However, I left the MUST for the repository as this TAP moves revocation for Fulcio identities to rekor (as you don't necessarily want to revoke the whole identity, but rather a set of certificates associated with that identity), and thus needs to check for revocation of certificates using Rekor at the time of use.

2022-04-29 07:25 UTC, jku commented
>I left the MUST for the repository as this TAP moves revocation for Fulcio identities to rekor (as you don't necessarily want to revoke the whole identity, but rather a set of certificates associated with that identity), and thus needs to check for revocation of certificates using Rekor at the time of use.

Can you specify what you mean by "time of use"? If we're still talking about the time when signature is submitted to the repository, I think these hold:
* certificate is short lived
* we can require that certificate is valid at time of processing

as a consequence, the idea that the certificate has been revoked during the few seconds it has existed is pretty theoretical.

The repository could (and probably should) check revocations of certificates used in metadata periodically but that does not seem to be what the TAP is suggesting.

2022-06-24 15:17 UTC, mnm678 commented
> Can you specify what you mean by "time of use"? If we're still talking about the time when signature is submitted to the repository, I think these hold:
> 
>     * certificate is short lived
> 
>     * we can require that certificate is valid at time of processing
> 
> 
> as a consequence, the idea that the certificate has been revoked during the few seconds it has existed is pretty theoretical.
> 
> The repository could (and probably should) check revocations of certificates used in metadata periodically but that does not seem to be what the TAP is suggesting.

I agree that the short-lived certificate probably won't be revoked during it's valid period, if an attacker was able to maliciously sign a package on behalf of a user, the repository needs some way to detect this. I think your suggesting of having the repository do periodic checks might be a more efficient way to achieve this.

2022-06-27 11:21 UTC, jku commented
I admit I don't have a complete picture of how the revocations would work (let's say in a PyPI-like case) but I still don't think making Rekor a MUST is useful (I don't think TUF requires checking GPG key revocations either). 

At the very least it needs to be specified **when** exactly the repository should be querying Rekor: I don't understand how to implement this requirement at the moment.

2022-07-26 15:04 UTC, mnm678 commented
@jku 

Looking at this with fresh eyes, I agree that Rekor should not be required. I removed the requirement, but also made it clear what the tradeoffs are for clients that decide not to do this check (slightly more risk in the case of a repository compromise). I also clarified how revocation would work with this TAP, as I think that was part of my concern before.

2022-07-28 07:17 UTC, haydentherapper requested changes

2022-07-28 07:17 UTC, haydentherapper commented on candidate-fulcio-tap.md
> +In addition, the repository SHOULD, and clients MAY additionally query the Rekor transparency log to ensure that the Fulcio certificate is valid at the time that it was issued. To do so the user can
I think this step should be a MUST for a couple of reasons:

1) It guarantees that the issued certificate was valid when the signature was generated. It's unlikely that clients will verify signatures at the time when the certificate is still valid, so I'd rather just always require querying.
2) It guarantees that the certificate is in the log, and so we know that it is auditable.

2022-07-28 07:17 UTC, haydentherapper commented on candidate-fulcio-tap.md
> +In cases where online verification is not possible, stapled inclusion proofs (i.e., evidence gathered by the signer from the log) MAY be presented alongside the software and signature. The client MAY
Can this be relaxed to support the offline "SET bundles" of the signed timestamp and entry? Those don't include inclusion proofs, they're more like promises of inclusion, but they are signed by the log signer (same signer as what signed the tree heads), and so the trust model is the same.

2022-07-28 07:17 UTC, haydentherapper commented on candidate-fulcio-tap.md
> +In addition to developer monitoring, the TL SHOULD have auditors that watch the log for any suspicious activity. If something bad is found in the TL, then auditors MUST indicate this to clients to en
> something bad

Can we specify what we mean by bad? Things like "the log was found to be mutated, the log was not operating as append-only, the log provided invalid inclusion proofs"?

2022-07-28 07:17 UTC, haydentherapper commented on candidate-fulcio-tap.md
> +In addition to developer monitoring, the TL SHOULD have auditors that watch the log for any suspicious activity. If something bad is found in the TL, then auditors MUST indicate this to clients to en
Do we have a format for the multi-role delegations and how to include an auditor signature? Do we have more details on how an auditor would revoke their signature?

2022-07-28 07:17 UTC, haydentherapper commented on candidate-fulcio-tap.md
> +If the bad certificates are due to a compromised Fulcio server, the Fulcio server MUST be revoked using the root of trust.
> the Fulcio server MUST be revoked using the root of trust.

nit, suggest rephrasing: "Fulcio must revoke its certificate, distribute a new certificate in the TUF Sigstore root of trust, and inform clients of the compromise"

2022-07-28 07:17 UTC, haydentherapper commented on candidate-fulcio-tap.md
> +This TAP improves security by eliminating the risk of developers losing their keys if they chose to use Fulcio instead of a traditional public key cryptosystem. However, it adds 2 additional services
3 services, also the identity provider

2022-07-28 07:17 UTC, haydentherapper commented on candidate-fulcio-tap.md
> +If a developer's OIDC credentials are compromised, the developer SHOULD use existing TUF processes for revocation. Specifically they SHOULD ask the delegator to replace any metadata that includes the
One question with this, and this topic has come up too when thinking about artifact revocation: How does a delegator recognize the difference between a developer whose accounts has been compromised requesting a change of delegation, and an attacker who compromised an account and is requesting a change of delegation to an account they control?

2022-07-28 07:17 UTC, haydentherapper commented on candidate-fulcio-tap.md
> +
It also worth considering a compromised identity provider who issues ID tokens with arbitrary/attacker-controlled identities

2022-07-28 07:17 UTC, haydentherapper commented on candidate-fulcio-tap.md
> +If the Fulcio server is compromised, it may issue certificates on behalf of any attacker who uses Fulcio to verify their identity. However, the Fulcio server is backed by offline keys that are signed
> However, the Fulcio server is backed by offline keys that are signed by TUF root keys, and so it is possible to recover from any Fulcio server compromise

I'd suggest a slight rephrasing, this reads like the Fulcio CA signing key is offline, which isn't accurate. 

I'd also add to that it's possible to recover by distributing a new Fulcio root through the TUF Sigstore root of trust. (Maybe a meta comment, it's probably worth noting early on that the Fulcio and Rekor verification material is distributed via TUF)

2022-07-28 07:17 UTC, haydentherapper commented on candidate-fulcio-tap.md
> +If the Fulcio server is compromised, it may issue certificates on behalf of any attacker who uses Fulcio to verify their identity. However, the Fulcio server is backed by offline keys that are signed
It might be worth clarifying they are 2 tlogs - Fulcio has a CT log, and there's also Rekor. It's worth considering either being compromised, and that both can be used for auditing.

2022-07-28 07:17 UTC, haydentherapper commented on candidate-fulcio-tap.md
> +If only the transparency log is compromised, the attacker will not be able to do anything without cooperation from the Fulcio server. However, if the attacker compromises both the Fulcio server and t
> If only the transparency log is compromised, the attacker will not be able to do anything without cooperation from the Fulcio server

Suggest rephrasing to mention that this is because an attacker can't fetch a valid identity-bound certificate without a compromised Fulcio instance.

2022-07-28 07:17 UTC, haydentherapper commented on candidate-fulcio-tap.md
> +If only the transparency log is compromised, the attacker will not be able to do anything without cooperation from the Fulcio server. However, if the attacker compromises both the Fulcio server and t
> recovered

nit: Not really recovered, I think of that more for availability. It's that we can regenerate the key material and securely distribute it.

2022-07-28 18:04 UTC, mnm678 commented on candidate-fulcio-tap.md
> +    "root-cert": ROOT_CERTIFICATE
Not all TUF clients will verify using Rekor, so including the root certificate here means that clients don't have to make network calls outside the usual TUF process. TUF allows for revocation, etc of anything in the metadata, including this field, and so listing the root cert here limits the impact of a compromised Fulcio server.

2022-07-28 18:04 UTC, mnm678 commented on candidate-fulcio-tap.md
> +    { "keyid" : KEYID,
Yes and no, the keyid is used by TUF as a "hint" so that the verifier can determine which signing key/identity is trusted to sign a particular piece of metadata. So it's needed for interaction with other parts of TUF.

2022-07-28 18:05 UTC, mnm678 commented on candidate-fulcio-tap.md
> +In addition, the repository SHOULD, and clients MAY additionally query the Rekor transparency log to ensure that the Fulcio certificate is valid at the time that it was issued. To do so the user can
This was required at first, but @jku convinced me that the main goal of checking Rekor is to ensure timeliness, which is not needed if the metadata is uploaded within the validity window of the Fulcio certificate.

2022-07-28 18:06 UTC, mnm678 commented on candidate-fulcio-tap.md
> +If a developer's OIDC credentials are compromised, the developer SHOULD use existing TUF processes for revocation. Specifically they SHOULD ask the delegator to replace any metadata that includes the
This is a really good question. The easy answer is "a trusted communication channel", but if a developer's email account is compromised it could be challenging to find a con-compromised communication channel. If the attacker starts behaving badly (uploading malware, etc), this could be detected and the identity revoked, but if the attacker is less obvious this would be hard.

I'm going to say this problem is out of scope for this TAP (as it was already a problem before), but we should keep discussing it.

2022-07-28 18:08 UTC, mnm678 commented
Thanks for the review @haydentherapper! I left a few responses

2022-08-01 17:17 UTC, haydentherapper commented on candidate-fulcio-tap.md
> +In addition, the repository SHOULD, and clients MAY additionally query the Rekor transparency log to ensure that the Fulcio certificate is valid at the time that it was issued. To do so the user can
Yea, it makes sense that Rekor not be a requirement since this TAP is not about artifact signing. Maybe we can get the best of both worlds, and still not require Rekor. I mentioned that Fulcio publishes its certificates to its own certificate transparency log. What about mandating that the certificate was uploaded to a CT log when the certificate was valid?

2022-09-13 11:28 UTC, haydentherapper commented on candidate-fulcio-tap.md
> +In addition, the repository SHOULD, and clients MAY additionally query the Rekor transparency log to ensure that the Fulcio certificate is valid at the time that it was issued. To do so the user can
Just was thinking more about this recently. 

Rekor provides two things - the ability to audit an identity is public, and a time of inclusion to verify expired certificates.

We should separate these two. The former should remain optional if Rekor is involved. It is ideal to make sure users are receiving the same set of keys as others, but I recognize that we want to avoid requiring Rekor. I think i did mention in another comment that all certs are written to the fulcio certificate transparency log, so possibly we could make checking either inclusion or an SCT a requirement? (Note SCTs are included in the certificates, so checking these should be trivial)

I think we need to mandate checking expiration however. This can come in three forms:
* Rekor proof
* A Rekor SET for offline checks 
* A signed timestamp

The last bullet point is what we’ve thinking more about recently. Time stamps could be RFC3161 for example. Sigstore is planning to operate a time stamp authority, or users could fetch a time stamp from a third party time stamp authority like Digicert.

2022-10-29 14:37 UTC, JustinCappos reviewed
Jotting down some initial thoughts / questions.  I need to go through it again once I understand my current points of confusion better.

2022-10-29 14:37 UTC, JustinCappos commented on candidate-fulcio-tap.md
> +Using this mechanism, the developer requests a certificate from Fulcio, Fulcio verifies the developer's identity using OIDC, the developer uses the signing key listed in the certificate to sign their
I don't really get how one delegates to someone in this case.  I assume you are delegating to an OIDC identity / issuer / root tuple, but it seems like a common use case will be that people add / remove OIDC identities and primarily the repository is aware of this.  So, in this case, it feels like you need something like TAP 8 key self rotation to forward your delegations to your new set of identities.

For example, if Marina delegates to (justin@example.com, google.com, ...) and then I add (justin@example.com, facebook.com, ...), I don't understand how her delegation will work.  

Actually, I've just realized I don't fully understand if me having two OIDC identities in this case works well at all.  It seems like there would need to be a delegation from one to set of them to handle this.  But even in the case where I know I want to allow both, how do I do this so that I don't store keys for either, yet can revoke trust for either one without delegations, etc. breaking?  

TAP 8 would address this in many ways, but I feel like I'm still not seeing the complete picture clearly.

2022-11-01 14:12 UTC, jku commented on candidate-fulcio-tap.md
> +In addition to supporting existing TUF targets delegations, this TAP adds support for delegations to any OIDC identity, including developer email addresses, to be verified by Fulcio. These delegation
offline verification of even the timestamp is possible but I suppose that would require including the Signed Entry Timestamp in the signature as well (I've understood this would be slightly less secure as we then don't confirm the entry is part of the rekor log, only that it has been signed by correct rekor keys).

I'd still be interested in hearing why the timestamp checks are absolutely necessary here -- TUF doesn't do any of that for other signatures either -- I'm wondering what sort of new attacks are enabled by (optionally) not checking the validity time.

2022-11-01 14:33 UTC, jku commented on candidate-fulcio-tap.md
> +    "root-cert": ROOT_CERTIFICATE
@haydentherapper you are probably right that this is too much detail... I believe the point here was that we need to identify the sigstore instance somehow, right? How does the TUF client know it should use the sigstore.dev services?

2022-11-01 14:47 UTC, jku commented on candidate-fulcio-tap.md
> +* Use the generated private key to sign targets metadata, then include the certificate in ‘signatures’ as indicated above
this is all true... but this is handled by sigstore client: I don't think we need to define it here (we don't document the RSA signing in detail either)

2022-11-01 16:13 UTC, mnm678 commented
@znewman01 and I had a discussion today about this TAP and some of @JustinCappos's  concerns. Here is a summary of what we talked about, and the plan moving forward. I'll include the relevant comments inline and in the TAP as well.

* Certificates in this TAP: There are two types of certificates mentioned, Fulcio root certificates and certificates needed for verification.
   * The root certificates are currently listed in the delegation, leading to repetition and making it so that a certificate would have to be replaced in many places in case of revocation or rotation.
To solve this, I will update the TAP to state that clients should use Sigstore’s root of trust to distribute Fulcio root certificates
   * For verification, this TAP lists the signature and certificate, however, these fields are not enough for offline verification.
To solve this, I will update the TAP to clarify that the signature should contain all the information from a Rekor bundle (certificate, signature, signed tree head)

* How do delegations to Fulcio identities get updated?
If these delegations are from online keys, they are less secure against repository compromise but allow for dynamic use of new Fulcio identities. If they are offline, they are more secure, but do not allow for dynamic use of new identities.
This problem should be addressed when using this TAP as part of an integration.
This is a similar tradeoff for online and offline keys that exists in TUF today. Implementations should prefer the use of offline keys for delegations except where this is infeasible. TAP 8 may improve the usability of offline delegations in the future.

* Which OIDC providers should be supported?
Initially, these should be defined by a client configuration (right now, Fulcio only supports 2 of them). As part of TAP 8, we may want a mechanism to define which key types should be used for a particular delegation, including which OIDC providers are trusted.

* Does TUF still need a timestamp and snapshot when we integrate with Rekor?
This should be discussed more as we add TUF functionality to cosign and other Sigstore clients. For this TAP timestamp and snapshot are still necessary.

* How do we manage the Sigstore root of trust?
We now rely on the Sigstore root of trust to distribute Fulcio keys. This root of trust is backed by TUF, and so clients should be able to use it with their existing TUF client.

* Offline verification
The verification mentioned above using the certificate, signature, and signed tree head can be done offline. Online verification allows the client to additionally check that the signed tree head is also included in the current tree head.
I will clarify this in the TAP, and state that online verification should be available to clients, but not required.

2022-11-01 16:46 UTC, jku commented
> * The root certificates are currently listed in the delegation, leading to repetition and making it so that a certificate would have to be replaced in many places in case of revocation or rotation.
> To solve this, I will update the TAP to state that clients should use Sigstore’s root of trust to distribute Fulcio root certificates

Does this mean we hard code the current public instance as the only fulcio/rekor combo that can be used? 

> * How do delegations to Fulcio identities get updated?
> If these delegations are from online keys, they are less secure against repository compromise but allow for dynamic use of new Fulcio identities. If they are offline, they are more secure, but do not allow for dynamic use of new identities.

True but this has nothing to do with fulcio identities: The process is 100% identical regardless of the delegated identity/keytype

> * Does TUF still need a timestamp and snapshot when we integrate with Rekor?
> This should be discussed more as we add TUF functionality to cosign and other Sigstore clients. For this TAP timestamp and > snapshot are still necessary.

A fine question but that would really define a new/different protocol so I agree: not a discussion for this TAP.

2022-11-01 18:49 UTC, mnm678 commented
> > * The root certificates are currently listed in the delegation, leading to repetition and making it so that a certificate would have to be replaced in many places in case of revocation or rotation.
> >   To solve this, I will update the TAP to state that clients should use Sigstore’s root of trust to distribute Fulcio root certificates
> 
> Does this mean we hard code the current public instance as the only fulcio/rekor combo that can be used?

The client could do one-time setup to point to any Fulcio instance. I don't like the idea of pointing to the root cert here when it's already distributed through the TUF root of trust, which has better revocation and rotation than including it in a bunch of delegations. The limit of one Fulcio instance is the main downside to this approach. Alternately I could switch pack to including a url to the Fulcio root here, but then we're relying on TLS as the only security. 

If we need multiple Fulcio instances, we could add a TAP 4 style mapping for each target, but this seems like a lot of complexity unless there's a firm use case. Happy to hear your thoughts on this.

> 
> > * How do delegations to Fulcio identities get updated?
> >   If these delegations are from online keys, they are less secure against repository compromise but allow for dynamic use of new Fulcio identities. If they are offline, they are more secure, but do not allow for dynamic use of new identities.
> 
> True but this has nothing to do with fulcio identities: The process is 100% identical regardless of the delegated identity/keytype

I agree, this doesn't require a change to TUF or the TAP, but it should be considered when implementing, it could maybe be added to supplemental documentation per theupdateframework/specification#91.

2022-11-03 20:12 UTC, asraa commented
> Does TUF still need a timestamp and snapshot when we integrate with Rekor?

Leaving this as documentation. There's no way to query for an artifact reliably on Rekor without knowing the artifact already. e.g. I can't ask "is there a later version of snapshot on the log, or is the one I have, 5.root.json, the latest?" So I think yes, you still need it, but I think there's no way for clients to "search" the log for the latest without having a hint. Validating its existence on Rekor will only give you a global assurance that it was published after the previous because of the monotonicity of the log.

2022-11-03 20:18 UTC, asraa commented on candidate-fulcio-tap.md
> +In addition to supporting existing TUF targets delegations, this TAP adds support for delegations to any OIDC identity, including developer email addresses, to be verified by Fulcio. These delegation
Yes: would require distributing the Signed Entry Timestamp (similar to SCT) to the verifiers. It could be alongside the signature, not necessarily in the metadata. 

> slightly less secure as we then don't confirm the entry is part of the rekor log

Yes! You don't get log inclusion from this; so you don't get the portion of "is this part of everyones global view", and "did rekor actually store this entry in the log"? 

one thing to note is that the timestamp is NOT part of the log entry, so it's not part of the immutable content of the log. rekor just stores the integrated time of an entry into the backing database (unsigned in the db, so log operators can tamper with it). "the timestamped Rekor transparency log" is a little misnomer because right now (although we're working on it!) it doesn't provide independently verifiable timestamps.

2022-11-03 20:22 UTC, asraa commented on candidate-fulcio-tap.md
> +The root certificate or certificate chain for the Fulcio server MUST be obtained using the Sigstore root of trust.
how can a user differentiate between custom sigstore roots, like the staging or prod instances in order to get the right trusted material for Fulcio? the user definitely needs to be communicated what its trust roots are out of band, but as a hint, maybe something in the keyval can reference the root.. like the root certificate issuer?
```
"root-issuer": "Sigstore Staging"
```

2022-11-03 20:23 UTC, asraa commented on candidate-fulcio-tap.md
> +Where BUNDLE is an object that contains the transparency log verification information, Fulcio X.509 signing certificate, and a signature over targets metadata, conforming to the [format defined by Si
```suggestion
Where BUNDLE is an object that contains the verification information (transparency log references or timestamps), Fulcio X.509 signing certificate, and a signature over targets metadata, conforming to the [format defined by Sigstore](https://github.com/sigstore/protobuf-specs/blob/main/protos/sigstore_bundle.proto). The transparency log verification information includes a signed timestamp (SET) from Rekor promising inclusion in the Rekor transparency log.
```

2022-11-03 20:24 UTC, asraa commented on candidate-fulcio-tap.md
> +* Upload the certificate, signature, and hash of the targets metadata to the timestamped Rekor transparency log. Rekor will return an SET with a timestampe that indicates that Rekor recieved the requ
```suggestion
* Upload the certificate, signature, and hash of the targets metadata to the timestamped Rekor transparency log. Rekor will return an SET with a timestamp that indicates that Rekor received the request and will include it in the log.
```

2022-11-03 20:24 UTC, asraa commented on candidate-fulcio-tap.md
> +This signature, and the associated Rekor timestamp obtained by querying the Rekor server, MUST be verified by the repository and MAY be verified by the end user. The verifier MUST obtain the Rekor ro
> obtain the Rekor root keys using a secure offline method prior to verifying the signature and associated certificate.

If they obtain it via TUF does that count as offline? The initial root is offline :)

2022-11-03 20:25 UTC, asraa commented on candidate-fulcio-tap.md
> +* Verify the signature on the certificate to ensure that the signature chains up to the trusted Fulcio root.
Optionally (or maybe not @haydentherapper ) verify the certificate's inclusion in the CT log with the trusted certificate log public key (obtained out of band)

2022-11-03 20:26 UTC, asraa commented on candidate-fulcio-tap.md
> +* Verify the SET to ensure that the certificate was included in the Rekor transparency log.
```suggestion
* Verify the SET to ensure that the signature was signed during certificate validity
```

Verifying a SET does not actually give you the validity that it was included, just a promise. If you did online verification you could verify the inclusion proof.

2022-11-03 20:27 UTC, asraa commented on candidate-fulcio-tap.md
> +* Query the Rekor transparency log for a proof of inclusion against the certificate included in the TUF metadata
```suggestion
* Query the Rekor transparency log for a proof of inclusion against the certificate and TUF metadata
```

You'd need both the certificate and TUF metadata for the query

2022-11-03 20:28 UTC, asraa commented on candidate-fulcio-tap.md
> +	* Verify this consistency proof.
```suggestion
	* Verify this consistency proof.
	* Persist the newest signed tree head
```

2022-11-03 20:28 UTC, asraa commented on candidate-fulcio-tap.md
> +* Verify this inclusion proof.
```suggestion
* Verify this inclusion proof.
* Verify that the root hash of the inclusion proof is consistent with the signed tree head verified in step 1
```

2022-11-03 20:30 UTC, asraa commented on candidate-fulcio-tap.md
> +* Verify this inclusion proof.
Honestly, I'd remove step 1 in favor of 

```
* Query the Rekor transparency log for a proof of inclusion against the certificate included in the TUF metadata
* Verify this inclusion proof.
* Verify that the root hash of the inclusion proof is consistent with your current signed tree head.
* Persist the signed tree head corresponding to the inclusion proof's root hash.
```

This way you only have to verify consistency once

2022-11-03 20:35 UTC, asraa commented on candidate-fulcio-tap.md
> +By default, clients will perform offline verification. They may choose to additionally perform online verification. In practice, exisiting uses of transparency logs use offline verification as it sav
```suggestion
By default, clients will perform offline verification. They may choose to additionally perform online verification. In practice, exisiting uses of transparency logs use offline verification as it saves bandwidth and maximum merge delays on the transparency log mean that onlie verification is not immediately available. This is because the transparency log will batch additions to the log. Offline verification relies on a signature from the Rekor key that the entry will be included and that the entry was seen at a certain time. This is the same key that signs the Rekor signed tree head in online verification. If the Rekor key is compromised, both of these verification types could be tricked. However, monitors are able to detect bad behavior once entries are added to the log, and monitor signatures can be used to provide additional assurance.
```

2022-11-03 22:16 UTC, znewman01 commented on candidate-fulcio-tap.md
> +* Verify the SET to ensure that the certificate was included in the Rekor transparency log.
You don't want to block package publication on the merge, though, so you can't wait for Rekor to catch up (you can today because there is no merge delay, but I don't think we should rely on that behavior).

Below it says clients MAY do online verification which I think is the right recommendation. Maybe SHOULD?

2022-11-03 22:17 UTC, znewman01 commented on candidate-fulcio-tap.md
> +This signature, and the associated Rekor timestamp obtained by querying the Rekor server, MUST be verified by the repository and MAY be verified by the end user. The verifier MUST obtain the Rekor ro
Yeah, "out of band" might be better here

2022-11-03 22:21 UTC, znewman01 commented on candidate-fulcio-tap.md
> +The root certificate or certificate chain for the Fulcio server MUST be obtained using the Sigstore root of trust.
I just sent you a doc (for drive-by observers: if it's not available publicly by Nov 7 2022, annoy me here!) but tl;dr:

- For this TAP, we're assuming one Sigstore instance that's agreed upon by clients/repos. This isn't terribly satisfying but probably works most of the time.
- I think you're right about sticking something in the key (or maybe changing the scheme) in the medium term.

2022-11-03 22:26 UTC, znewman01 commented on candidate-fulcio-tap.md
> +In addition to supporting existing TUF targets delegations, this TAP adds support for delegations to any OIDC identity, including developer email addresses, to be verified by Fulcio. These delegation
> I'd still be interested in hearing why the timestamp checks are absolutely necessary here -- TUF doesn't do any of that for other signatures either -- I'm wondering what sort of new attacks are enabled by (optionally) not checking the validity time.

The certificate in Sigstore is only valid for ~10 minutes, so you want to check that the signature was made during the validity period. Everything else in TUF needs to be unexpired at the time of verification. 

This mitigates the damage you can do with a weak/leaked Sigstore ephemeral key.

2022-11-04 14:14 UTC, asraa commented on candidate-fulcio-tap.md
> +* Verify the SET to ensure that the certificate was included in the Rekor transparency log.
Oh I agree! I just wanted to clarify the wording: I think SET verification is to validate the signature was creating during the cert validity period. technically, verification doesn't *require* inclusion in the tlog, although that's a nice property to have. but i don't think you can totally get that without online verification

MAY vs SHOULD: SHOULD if their client can wait for the response? otherwise MAY, either or

2022-11-04 17:44 UTC, mnm678 commented on candidate-fulcio-tap.md
> +* Verify this inclusion proof.
Establishing the current tree head first allows the verifier to ensure that the head they're using is current and allows them to batch multiple verifications (especially for auditors who will be checking a bunch of different entries at once)

2022-11-04 17:44 UTC, mnm678 commented on candidate-fulcio-tap.md
> +This signature, and the associated Rekor timestamp obtained by querying the Rekor server, MUST be verified by the repository and MAY be verified by the end user. The verifier MUST obtain the Rekor ro
Yeah, in the case of the Sigstore instance this means "do TUF verification". I'll use "out of band" to make this more clear.

2022-11-04 17:53 UTC, haydentherapper commented on candidate-fulcio-tap.md
> +* Verify the signature on the certificate to ensure that the signature chains up to the trusted Fulcio root.
I think this is a requirement if you are using the public Fulcio instance. You want to know that identity certificates are auditable.

2022-11-04 17:55 UTC, haydentherapper commented on candidate-fulcio-tap.md
> +* Verify the SET to ensure that the certificate was included in the Rekor transparency log.
It's an interesting idea to wait for the merge, but I think this can be implemented by the repositories, a periodic check for inclusion in the log. Maybe something like a checkmark (sorry, ive been on twitter too much recently) once it's verified inclusion

2022-11-04 18:17 UTC, mnm678 commented on candidate-fulcio-tap.md
> +* Verify the signature on the certificate to ensure that the signature chains up to the trusted Fulcio root.
Is this not included in step 3 here? (verify the SET)

2022-11-04 18:19 UTC, haydentherapper commented on candidate-fulcio-tap.md
> +* Verify the signature on the certificate to ensure that the signature chains up to the trusted Fulcio root.
They're separate logs. What if someone doesn't want to use Rekor? If you don't need public auditability and you only use Rekor for timestamping, once we add in functionality for using other timestamping mechanisms, then Fulcio + signed timestamp is sufficient.

2022-11-04 18:21 UTC, mnm678 commented on candidate-fulcio-tap.md
> +* Verify the signature on the certificate to ensure that the signature chains up to the trusted Fulcio root.
Oh, so this is verify the Fulcio certificate is included in a CT log?

2022-11-04 18:22 UTC, haydentherapper commented on candidate-fulcio-tap.md
> +* Verify the signature on the certificate to ensure that the signature chains up to the trusted Fulcio root.
Yep exactly! There's an open question of if we really need a CT log in addition to Rekor, but if there will be clients who only care about code signing without auditability, I think it is useful to maintain a separate log just for Fulcio certs.

2022-11-04 18:24 UTC, mnm678 commented on candidate-fulcio-tap.md
> +* Verify the signature on the certificate to ensure that the signature chains up to the trusted Fulcio root.
Got it, adding this step

2023-01-13 20:05 UTC, mikhailswift commented
Apologies if any of this is a bit off base or not the correct avenue, I'm still familiarizing myself with TUF a bit so I very well may have some core misunderstandings. Please correct me if so.

I see some overlaps with this functionality and the some use cases we have for defining Roles using SPIFFE/SPIRE short-lived certificates. Where this is focused around verifying the OIDC identity using the Fulcio issued certificate we want to do similar by constraining on a specified SPIFFE ID on a SPIFFE issued certificate.

I'm wondering if they may be some way we can come to a common solution for both? Or if perhaps creating a base PKI key type that both the sigstore and SPIFFE implementations could extend for their specific requirements?

2023-01-13 20:32 UTC, mnm678 commented
> I see some overlaps with this functionality and the some use cases we have for defining Roles using SPIFFE/SPIRE short-lived certificates. Where this is focused around verifying the OIDC identity using the Fulcio issued certificate we want to do similar by constraining on a specified SPIFFE ID on a SPIFFE issued certificate.
> 
> I'm wondering if they may be some way we can come to a common solution for both? Or if perhaps creating a base PKI key type that both the sigstore and SPIFFE implementations could extend for their specific requirements?
> 
> I've done some with with in-toto [ITE7](https://github.com/in-toto/ITE/blob/master/ITE/7/README.adoc) for similar types of functionality with regards to defining functionaries with PKI issued keys, if that's relevant at all here.

I think that we can certainly have a similar mechanism for using SPIFFE/SPIRE identities with TUF.

My main reason for keeping this proposal limited to Fulcio is to simplify the fields required in the delegation and signature, and ensure that each key type has all fields that are needed for a secure implementation. For example, the Sigstore bundle in the signature is vital for the security of Fulcio signatures.

2023-01-17 21:28 UTC, mnm678 commented
@JustinCappos @trishankatdatadog @joshuagl are we ready to merge this as a draft?

2023-01-18 11:34 UTC, JustinCappos approved these changes
I'm fine merging as draft.  I would like to have someone from the Sigstore side also review this before moving the TAP to accepted.  Ideally we would have more clarity around monitoring TLs, etc. at that time too...

2023-01-18 15:00 UTC, znewman01 commented
> someone from the Sigstore side also review this 
Consider this comment an IOU. I'll also circulate it more generally.

>  Ideally we would have more clarity around monitoring TLs, etc. at that time too...
@SantiagoTorres is pushing hard on this on the Sigstore end so I bet he'll be a good source for updates. I think @mnm678 is also thinking about TUF<->TL interactions more generally as well.

2023-01-25 18:32 UTC, lukpueh reviewed
Great write-up, Marina! I think this will be fun to implement, e.g. for python-tuf using the new [signer API](https://github.com/theupdateframework/python-tuf/pull/2276).

I left a couple of minor comments inline, admitting that I don't know sigstore well enough for a detailed review of the signing and verification workflows.

I do have two high-level comments:

1. Talking about "repository" and "developer" in this TAP, requires some implicit assumptions about a particular TUF setup. Likely something like PEP 480. For the sake of generality and clarity I wouldn't make those assumptions. Instead, I would limit the scope  to the specification of the new key and signature metadata formats, and the signature creation and verification (online and offline), plus monitoring routines.

2. A more vague and very high-level observation: We are conflating two PKIs here, which both seem to offer similar concepts like key hierarchies, expiry, revocation, etc. I can't pin-point a particular problem with that, I just want us to make extra sure that those concepts are not in conflict with each other, or add extra complexity to TUF without a practical security advantage.
I mention this, because I just made a similar realization with gpg keys and signatures and redundant delegation and expiration checks.


Oh, and some more minor nit-picks (feel free to ignore):
- There's a random mix of `”` and `"` in this document. I suggest to `s/”/"/g`. (Same goes for `’` and `'`).
- Sentences in lists should end consistently with (or without) `.`.

2023-01-27 19:31 UTC, mnm678 commented on candidate-fulcio-tap.md
> +  “scheme”: "Fulcio",
It's possible that a different Fulcio instance could be used, which could be specified as a different scheme so that the correct CT log, etc are checked.

2023-01-27 19:34 UTC, mnm678 commented on candidate-fulcio-tap.md
> +      , ... ]
I linked to the Sigstore BUNDLE definition. I avoided repeating it here as I think that definition should be the source of truth (and will remain up to date)

2023-01-30 21:48 UTC, mnm678 commented
Thanks @lukpueh I updated the pr, and tried to generalize away from the "developer" and "repository" terms where possible. The main point is that someone is signing the metadata using an OIDC account, and some central entity is responsible for performing some Sigstore verification.

2023-02-02 12:44 UTC, lukpueh reviewed
Thanks for the updates. I think this is good to be merged as draft. I left a few non-critical comments.

2023-02-02 12:44 UTC, lukpueh commented on candidate-fulcio-tap.md
> +   "bundle":  BUNDLE
Nit
```suggestion
   "bundle": BUNDLE
```

2023-02-02 12:44 UTC, lukpueh commented on candidate-fulcio-tap.md
> +Signers SHOULD monitor the transparency log (TL)  and look for certificates associated with their OIDC accounts to look for unauthorized activity. If they see a certificate on the TL that they did no
Nit:
```suggestion
Signers SHOULD monitor the transparency log (TL) and look for certificates associated with their OIDC accounts to look for unauthorized activity. If they see a certificate on the TL that they did not issue, the signer SHOULD replace any compromised metadata (creating new Fulcio certificate), and ensure the security of their OIDC account. If the OIDC account cannot be recovered, the signer MUST contact the role that delegates to them to replace the delegation to their OIDC identity.
```

2023-02-02 12:44 UTC, lukpueh commented on candidate-fulcio-tap.md
> +* Verify the Fulcio certificate's inclusion in the CT log with the trusted certificate log public key.
Don't we need to be online to actually verify the inclusion in the CT log?

2023-02-02 18:41 UTC, mnm678 commented on candidate-fulcio-tap.md
> +* Verify the Fulcio certificate's inclusion in the CT log with the trusted certificate log public key.
Technically this is a verifying a promise of inclusion, which is included in the bundle. I'll fix that.

2023-02-02 19:25 UTC, mnm678 commented
Thanks @lukpueh!

If you think it's ready to be merged as a draft can you mark as approved?

2023-02-03 08:39 UTC, lukpueh approved these changes

2023-02-07 10:43 UTC, JustinCappos approved these changes
I think it's ready for draft status...

2023-02-07 12:35 UTC, joshuagl approved these changes
Thanks for continuing to drive this @mnm678 ! I am happy to merge this as a draft. I left a few minor comments, but we can easily handle those in a follow-on.

It would be good to get a 👍 from @znewman01 or another Sigstore expert before we do merge.

2023-02-07 12:35 UTC, joshuagl commented on candidate-fulcio-tap.md
> +* Last-Modified: 27/07/2021
Nit: this date is a long time in the past, should we update?

2023-02-07 12:35 UTC, joshuagl commented on candidate-fulcio-tap.md
> +Where IDENTITY is the OIDC identity of the party who is authorized to sign and ISSUER is the OIDC entity used by Fulcio for verification.
Nit: examples of IDENTITY and ISSUER would be nice. Can we include an example?

2023-02-07 12:35 UTC, joshuagl commented on candidate-fulcio-tap.md
> +The root certificate or certificate chain for the Fulcio server MUST be obtained using the Sigstore root of trust. The client MUST use a single Fulcio instance.
Nit: is it worth linking to https://github.com/sigstore/root-signing ? I wish we had a better client-facing doc for the Sigstore root of trust repo.

2023-02-07 12:35 UTC, joshuagl commented on candidate-fulcio-tap.md
> +```
An example would be nice here, too.

2023-02-07 12:35 UTC, joshuagl commented on candidate-fulcio-tap.md
> +* Create a bundle that contains the signature, Fulcio certificate, SET.
Nit: if this is the standard Sigstore signing workflow, can we just link to some Sigstore reference material?

2023-02-07 12:35 UTC, joshuagl commented on candidate-fulcio-tap.md
> +* Verify the SET to ensure that the signature was signed during certificate validity.
Nit: if this is the standard Sigstore verification workflow, can we just link to some Sigstore reference material?

2023-02-07 12:40 UTC, jku commented on candidate-fulcio-tap.md
> +```
Yes! Not seeing examples makes it really hard to evaluate the complete design (when reviewers need to paint the big picture in their heads). I can understand if you don't want to add them in the TAP, but they should exist somewhere.

2023-02-07 12:44 UTC, jku commented on candidate-fulcio-tap.md
> +* Create a bundle that contains the signature, Fulcio certificate, SET.
Agreed. A lot of different signing mechanisms have implementation details that the tuf spec does not cover -- like Yubikeys can have pin/touch policies, KMSs have unique ways of key creation etc. Why do we do this for sigstore?

2023-02-07 12:55 UTC, jku commented on candidate-fulcio-tap.md
> +As `sig` was removed from `signatures`, parsing of the signatures will fail for old clients.
Drafts don't need to be perfect so this isn't a show stopper... But did you consider leaving the sig in there?

I understand it's removed because it's likely in the bundle already. But if the sig was left in there, then older clients would be able to handle the metadata file properly -- the data just wouldn't be signed be enough keys (because the signature by an unsupported keytype could not be verified). If the sig is not there, then clients  will be unable to load the metadata at all, because the metadata is clearly incompatible with older spec versions.

I'm not sure there is a practical use case for this but it just feels like adding new key (and signature) schemes shouldn't be breaking changes if they don't have to be.

2023-02-07 13:54 UTC, znewman01 approved these changes
With my Sigstore maintainer hat on: this LGTM as a draft.

2023-02-07 13:54 UTC, znewman01 commented on candidate-fulcio-tap.md
> +As `sig` was removed from `signatures`, parsing of the signatures will fail for old clients.
IMO we could just stuff the bundle into the existing `signature` field. Should be more backwards compatible; I agree with the general sentiment.

2023-02-07 13:54 UTC, znewman01 commented on candidate-fulcio-tap.md
> +* Verify the SET to ensure that the signature was signed during certificate validity.
The best reference material is still a draft (client specification).

Perhaps we inline it for now with a plan to replace this later on

2023-02-07 13:54 UTC, znewman01 commented on candidate-fulcio-tap.md
> +The root certificate or certificate chain for the Fulcio server MUST be obtained using the Sigstore root of trust. The client MUST use a single Fulcio instance.
+1 to describing the root of trust better.

Also, this TAP at the moment is tied strongly to the single "public good" Sigstore instance. I think in practice that should be specified by the TUF repository---you want all clients to agree on the CA infrastructure to use!

For a draft this is probably fine.

2023-02-07 18:01 UTC, mnm678 commented on candidate-fulcio-tap.md
> +As `sig` was removed from `signatures`, parsing of the signatures will fail for old clients.
added in #168

2023-02-07 18:05 UTC, mnm678 commented
I'm going to merge this, with #168 as a followup to address some minor comments, and #169 to document future changes, especially those that are pending documentation from the Sigstore side.

2023-02-07 18:06 UTC, mnm678 commented on candidate-fulcio-tap.md
> +* Last-Modified: 27/07/2021
Addressed in #168

2023-02-07 18:06 UTC, mnm678 commented on candidate-fulcio-tap.md
> +The root certificate or certificate chain for the Fulcio server MUST be obtained using the Sigstore root of trust. The client MUST use a single Fulcio instance.
Added in #168, with a followup in #169 to link to any new Sigstore documentation.

2023-02-07 18:07 UTC, mnm678 commented on candidate-fulcio-tap.md
> +```
Documented in #169

2023-02-07 18:07 UTC, mnm678 commented on candidate-fulcio-tap.md
> +* Create a bundle that contains the signature, Fulcio certificate, SET.
Documented in #169

2023-02-07 18:07 UTC, mnm678 commented on candidate-fulcio-tap.md
> +* Verify the SET to ensure that the signature was signed during certificate validity.
Documented in #169

2023-02-07 18:10 UTC, merged