Re-design TAP 15 metadata format
theupdateframework/taps pull request #154
Opened 2022-05-04 18:39 UTC by mnm678

Address some discussion from #132 by moving succinct hashed bin delegations to a new object within delegations.

In this version I opted to keep `path_hash_prefixes`, although I added a note that this field may be removed later backwards-incompatible way.

For simplicity, this change states that only one of `succinct_roles` or `roles` may be included. This seems to cover the most common use cases. Users with less common use cases could set up a complicated delegation tree if they would like to combine namespaced delegations and succinct hashed bin delegations, but it can't be done in the same delegation.

cc @jku @MVrachev @JustinCappos @trishankatdatadog @lukpueh

2022-05-05 07:31 UTC, JustinCappos commented
I think it is worth being explicit about how a maintainer would get the same functionality as supporting allowing succinct hash delegations within a single targets file.

2022-05-05 07:47 UTC, jku reviewed
this looks about right to me. Martin is working on a prototype I believe so we should get some implementation comments soon.

2022-05-05 07:47 UTC, jku commented on tap15.md
> +succinct hashed bin delegations will be terminating. The
Hmm, I wonder if this is correct. It seems to prevent the idea of using e.g. multiple succinct delegations (say, "targets" delegating to "succinct1" and "succinct2" using normal non terminating delegations, and both of those contain a succinct_roles)? I think succinct delegations could even be always non-terminating as the parent delegation could specify terminating if it wants to...

(I admit I still don't know if multiple succinct delegations has a use case, just pointing this out)

2022-05-05 20:03 UTC, mnm678 commented on tap15.md
> +succinct hashed bin delegations will be terminating. The
Hmm, I think we can safely remove the option for multiple succinct delegations using the same workaround as for using both `roles` and `succinct_roles` (setting up multiple intermediate roles). I don't think that this will be common, and having only one succinct delegation per role simplifies the mechanism a lot.

That said, I don't have a strong preference for making these always terminating, it just seemed like a way to simplify the metadata.

2022-05-06 06:51 UTC, jku commented on tap15.md
> +succinct hashed bin delegations will be terminating. The
I wasn't trying to suggest multiple succinct delegations in one metadata; I was talking about a "normal" role that delegates to two roles that are both succinct. If they are automatically terminating, then that setup makes no sense: I think they should either always be non-terminating (as the parent delegation can always terminate if it wants to) or should include the terminating field.

2022-05-09 15:58 UTC, MVrachev commented
> this looks about right to me. Martin is working on a prototype I believe so we should get some implementation comments soon.

I have implemented the prototype and left a comment about it here: https://github.com/theupdateframework/python-tuf/issues/1943#issuecomment-1121282526.

2022-05-13 19:43 UTC, mnm678 commented
@MVrachev @jku @lukpueh 

I updated the TAP per our discussion today to change `prefix_bit_length` to `bit_length` and clarify a few things.

2022-05-16 07:47 UTC, lukpueh commented on tap15.md
> +        "name_prefix" : "alice.hbd-",
💯  for succinct names!

2022-05-16 10:04 UTC, MVrachev requested changes
There was a discussion about TAP 15 with TAP author @mnm678, @jku, @lukpueh, @abs007 and me where it was decided the following:
1. Succinct hash delegation and `roles` would be separated. `roles` will only be responsible for standard roles and no succinct hash delegations.
2. As a result of the first point `keyids` and `threshold` attributes were added to succinct hash delegation.
3. Succinct hash delegations and standard roles (the `roles` attribute) should not exist together in one delegations object.
4. Only one succinct hash delegation must exist. 
5. There are a couple of renames that we agreed on:
- `succinct_hash_delegations` → `succinct_roles`
- `delegation_hash_prefix_len` -> `bit_length`
- `bin_name_prefix` → `name_prefix`

2022-05-16 11:31 UTC, mnm678 commented on tap15.md
>  bin will be determined using the BIT_LENGTH and NAME_PREFIX.
Correct. I was referring to how the rolename is generated, but I think it's just confusing to put this here when it's already described a couple of paragraphs below

2022-05-19 10:56 UTC, joshuagl submitted a review, later dismissed
Big thanks to everyone involved in this effort. It's awesome to see the TAP evolve based on an effort to implement.

Succinct hashed bin delegations now look much easier to implement and much easier to recognise in metadata. 🎉

2022-05-19 10:56 UTC, joshuagl commented on tap15.md
> +2^BIT_LENGTH bins that use the included keyids and threshold. All
Nit: worth emphasising that all of the 2^BIT_LENGTH bins use the same keyids and threshold?
```suggestion
2^BIT_LENGTH bins which all use the specified keyids and threshold. All
```

2022-05-19 10:56 UTC, joshuagl commented on tap15.md
> +  ],)
```suggestion
  ],) |
```
as it's one of `roles` or `succinct_roles`

2022-05-23 20:43 UTC, joshuagl approved these changes

2022-05-25 12:59 UTC, lukpueh submitted a review, later dismissed
LGTM modulo one minor formatting/consistency nit and a metadata example issue that could be addressed in a follow-up PR.

2022-05-25 12:59 UTC, lukpueh commented on tap15.md
> +  ("succinct_roles" : {
```suggestion
  ], |
  "succinct_roles" : {
```

Not sure if this is correct, but it's consistent with `("path_hash_prefixes": ... | "paths": ...)` above, where we don't group the individual OR'ed elements but the whole thing.

2022-05-25 12:59 UTC, lukpueh commented on tap15.md
> +        "bit_length": 16,
The TAP does not mandate this, but for the implementation we decided that it makes sense to have fixed length role names within one succinct delegation, by zero-padding the bin number part of the role name, where necessary.

If there is an implicit recommendation in the TAP (you do apply zero padding in the example above; maybe there  should be an explicit recommendation?), then `bit_length: 16` would entail 4 digit bin numbers, i.e. `alice.hbd-0000` to `alice.hbd-ffff`.

2022-05-30 09:11 UTC, lukpueh approved these changes

2022-05-30 10:36 UTC, joshuagl approved these changes

2022-05-30 19:43 UTC, merged