Tap14 updates
theupdateframework/taps pull request #158
Opened 2022-07-26 17:56 UTC by mnm678

I updated TAP 14 based on some implementation questions from @abs007.

This replaces references to the now-rejected TAP 5 with TAP 13 and adds a new optional file to support a range of filesystem types.

2022-08-03 12:29 UTC, lukpueh requested changes
LGTM modulo one type and a request for clarification (see inline)

2022-08-03 12:29 UTC, lukpueh commented on tap14.md
> +sources. However, breaking changes may require that all top-level metadata
How is TAP 13 related to downloading targets metadata from multiple sources? AFAIU, TAP 13 requires 3rd parties to upload the custom top-level targets metadata to the central repository.

2022-08-03 12:30 UTC, lukpueh commented
I have an non-PR-related question about [the following sentence in the TAP](https://github.com/theupdateframework/taps/blame/b7f539a9c8292ee51b88d46ddcf308aac435beb8/tap14.md#L304-L306):

> This allows them to differentiate between metadata that is expired due to deprecation and metadata that is expired due to an attack.

What does "expired due to an attack" mean?

2022-08-03 21:15 UTC, znewman01 approved these changes

2022-08-03 21:15 UTC, znewman01 commented on tap14.md
> +The repository may also maintain a `supported-version` file so that the client
`supported-versions`?

2022-08-03 21:15 UTC, znewman01 commented on tap14.md
> +as OCI registries or html servers), the repository SHOULD include a
s/html/HTTP/?

2022-08-03 21:15 UTC, znewman01 commented on tap14.md
> +Not all TUF repositories have file systems that are able to list all directories
nit: it's less about the FS, and more about the mechanism by which the repository is served

2022-08-03 21:15 UTC, znewman01 commented on tap14.md
> +as OCI registries or html servers), the repository SHOULD include a
also: move the example parenthetical to the previous sentence?

2022-08-03 21:15 UTC, znewman01 commented on tap14.md
> +where `VERSION` is the name of a supported version in the format `version-number.0.0` (i.e. 2.0.0).
While we're messing with this TAP...I kinda hate that we use "2.0.0" to mean "any 2.x.y version", I find it confusing...can we replace with just "2"?

(probably not in this PR)

2022-08-04 08:59 UTC, lukpueh commented on tap14.md
> +where `VERSION` is the name of a supported version in the format `version-number.0.0` (i.e. 2.0.0).
Had the same thought while re-reading the TAP

2022-08-04 19:39 UTC, mnm678 commented on tap14.md
> +as OCI registries or html servers), the repository SHOULD include a
I want to avoid a double parenthetical in the previous sentence. I can re-work this bit if it's a big deal.

2022-08-04 19:41 UTC, mnm678 commented on tap14.md
> +where `VERSION` is the name of a supported version in the format `version-number.0.0` (i.e. 2.0.0).
Done. In my head the `2.0.0` is more clear, but it seems that this isn't true for others :)

2022-08-05 07:23 UTC, lukpueh commented on tap14.md
> +where `VERSION` is the name of a supported version in the format `version-number.0.0` (i.e. 2.0.0).
The name could also by 2.x.y. :D

2022-08-05 12:21 UTC, znewman01 commented on tap14.md
> +as OCI registries or html servers), the repository SHOULD include a
I just ask because when I ready "not all TUF repositories have .... in a folder (the equivalent of ...)" my brain was really desperate for an example.

Maybe I'd advocate for dropping the `ls` comparison:

> Some TUF repositories are distributed over channels which do not support enumerating the subdirectories of the repository (for example, OCI registries or HTTP servers). To facilitate client discovery of available major versions, the repository SHOULD ...

Not a huge deal either way

2022-08-05 16:47 UTC, joshuagl commented on tap14.md
> +delegated targets metadata may not be
is this prohibited, or just a possibility? if the latter, we may want to say "might not".

2022-08-05 16:47 UTC, joshuagl commented on tap14.md
> +directories and may maintain a `supported-versions` file.
```suggestion
directories and MAY maintain a `supported-versions` file.
```
or even SHOULD?

2022-08-05 16:47 UTC, joshuagl commented on tap14.md
>  up to the discretion of an implementer, but it should be used to encourage
nit: we typically refer to implementation as libraries implementing the spec, and TUF deployments as applications or integrations

2022-08-05 16:48 UTC, joshuagl commented on tap14.md
> +Not all TUF repositories have file systems that are able to list all directories
We really should remove the FS model from the spec, perhaps documenting the API the FS tree provides 🤔 
ref https://github.com/theupdateframework/specification/issues/103

2022-08-09 18:37 UTC, mnm678 commented on tap14.md
>  up to the discretion of an implementer, but it should be used to encourage
Does the update look right here?

2022-09-01 12:26 UTC, znewman01 commented on tap14.md
> +where `VERSION` is the name of a supported major version (i.e. 2).
What type is `VERSION`?

Should we indicate "major version 1, but no subfolder for it" separately?

2022-09-21 15:59 UTC, znewman01 commented on tap14.md
> +directories and SHOULD maintain a `supported-versions` file.
Nit: this is a little out-of-nowhere, maybe move it into the next paragraph? If you use this directory structure, you SHOULD ..."

2022-09-21 15:59 UTC, znewman01 commented on tap14.md
> +where `VERSION` is the integer name of a supported major version (i.e. 2).
For forwards-compat, I'd like to consider making version be an object with a "number" key:

```
{ "supported_versions" : [
    { "number": 1 },
    { "number": 2},
    ...
  ]}
```

This will allow users to express more sophisticated things, like "folder X is compatible with both 3 and 4". I don't know if we'll need that, but there are situations where you might want multiple neighboring repos for non-major-version reasons (e.g. deprecating the

We could also skip it for now and replace the format of "supported-versions.json". Should we version supported-versions.json then?

2022-09-21 15:59 UTC, znewman01 commented on tap14.md
> +For backwards compatability, version 1 should be assumed to be in the top-level
👍 , this will make implementations much simpler

2022-09-21 15:59 UTC, znewman01 commented on tap14.md
> +`supported-versions` file in the top of this directory structure that lists
`suppoerted-versions.json`?

2022-09-21 15:59 UTC, znewman01 commented on tap14.md
>  attacker is able to block access to a directory on the repository. This would
We talked briefly about having the root keys sign supported-versions.json. That feels reasonable to me, though maybe complicated.

2022-09-21 21:49 UTC, znewman01 commented on tap14.md
> +and `FOLDER_NAME` is the integer representing the folder containing metadata for
Integer? I'd expect string.

2022-09-21 21:49 UTC, znewman01 commented on tap14.md
> +`supported-versions` file in the top of this directory structure that lists
You change this here but it's inconsistent now 😛 , there's a bunch of places you use this file name.

2022-09-21 22:25 UTC, mnm678 commented on tap14.md
> +and `FOLDER_NAME` is the integer representing the folder containing metadata for
I guess a string of an integer makes the most sense

2022-09-21 22:44 UTC, znewman01 reviewed
Ahh, sorry to be annoying. I just had a bunch of worries come up

2022-09-21 22:44 UTC, znewman01 commented on tap14.md
> +where `MAJOR_VERSION` is the integer representing a supported major version (i.e. 2)
nit: e.g., not i.e.

2022-09-21 22:44 UTC, znewman01 commented on tap14.md
> +where `MAJOR_VERSION` is the integer representing a supported major version (i.e. 2)
but real comment: it might be nicer if you give a full example: `{ 2 : "2" }`

2022-09-21 22:44 UTC, znewman01 commented on tap14.md
> +where `MAJOR_VERSION` is the integer representing a supported major version (i.e. 2)
Oh, JSON keys can only be strings. I think you want `{ "version": 2, "path": "2" }`

2022-09-21 22:44 UTC, znewman01 commented on tap14.md
> +and `FOLDER_NAME` is the string representing the folder containing metadata for
Can folder name have more than one part?

2022-09-21 22:44 UTC, znewman01 commented on tap14.md
> +and `FOLDER_NAME` is the string representing the folder containing metadata for
Is there any way to trick a client into going out-of-repo by passing `../../.ssh/id_rsa` or something?

2022-09-23 12:35 UTC, znewman01 commented on tap14.md
> +and `FOLDER_NAME` is the string representing the folder containing metadata for
This is addressed now.

2022-09-23 12:35 UTC, znewman01 commented on tap14.md
> +and `FOLDER_NAME` is the string representing the folder containing metadata for
I *think* this is addressed? What if we say that clients MUST check that there's only `[a-z0-9-_]` characters in there (and same server side)

2022-09-23 13:42 UTC, mnm678 commented on tap14.md
> +and `FOLDER_NAME` is the string representing the folder containing metadata for
If this file is signed by root, I don't think the clients need an additional check for the folder name, but they could add one for defense in depth.

2022-09-25 02:52 UTC, trishankatdatadog reviewed
Thanks, Marina! My biggest concern is on why we need a signed `supported-versions.json` somewhere for repositories that don't support listing of what appear to files in what appear to be folders. Could we please consider simpler mechanisms?

2022-09-25 02:52 UTC, trishankatdatadog commented on tap14.md
> +The repository may also maintain a `supported-versions.json` file so that the client
Located where exactly? Perhaps in [`.well-known`](https://en.wikipedia.org/wiki/Well-known_URI)?

2022-09-25 02:52 UTC, trishankatdatadog commented on tap14.md
> +directories. In addition, repositories SHOULD maintain a `supported-versions.json` file
Isn't this redundant with the note above?

2022-09-25 02:52 UTC, trishankatdatadog commented on tap14.md
> +upgrades from version 1.x.x to version 2.0.0 may look like:
```suggestion
upgrades from version 1.x.y to version 2.0.0 may look like:
```

2022-09-25 02:52 UTC, trishankatdatadog commented on tap14.md
> +- 1.x.x metadata files
```suggestion
- 1.x.y metadata files
```

2022-09-25 02:52 UTC, trishankatdatadog commented on tap14.md
> +  |- 2.x.x metadata files
```suggestion
  |- 2.x.y metadata files
```

2022-09-25 02:52 UTC, trishankatdatadog commented on tap14.md
> +Not all TUF repositories have a mechanism that is  able to list all directories
```suggestion
Not all TUF repositories have a mechanism that is able to list all directories
```

2022-09-25 02:52 UTC, trishankatdatadog commented on tap14.md
> +`supported-versions.json` file in the top of this directory structure that lists
If we are going to discuss this here, why not just link to this section from all the references to it above?

More importantly, I'm not sure about this idea. Why add even more complexity, especially requiring signatures? Are there simpler workarounds?

2022-09-25 18:51 UTC, znewman01 commented
> My biggest concern is on why we need a signed supported-versions.json somewhere for repositories that don't support listing of what appear to files in what appear to be folders. Could we please consider simpler mechanisms?

@trishankatdatadog I think that's *most* repositories. For instance, go-tuf *only* has built-in support for HTTP remotes, and IIRC python-tuf is the same, but HTTP doesn't have a (standard/uniform) way to list the contents of a directory. We ran into this when attempting to build out TAP-14 support in python-tuf.

We're open to alternatives suggestions, of course. The first thought was to stick an `index.txt` file in each folder, but if there's a lot of root metadata files that gets annoying really quickly. So then we decided to filter it down to just a list of folders containing supported versions, but v1.x.y is a funky special-case (do we call it `1/` or `/`) so we figured being explicit was better.

Signing is something that feels appropriate to me as a "better safe than sorry" thing. I think we could get away with *not* requiring it, but it feels nicer to me to have the roots sign off on something as consequential as a major version transition.

2022-09-26 16:05 UTC, mnm678 commented on tap14.md
> +`supported-versions.json` file in the top of this directory structure that lists
The signatures are to prevent a potential spec version freeze attack. This might not be the biggest concern as spec version upgrades should be rare, and once the client upgrades they can choose to not support the previous spec version, so happy to debate the signature part (especially as DoS attacks more generally are out of scope).

But users in some repos (like ones that use https) will need some mechanism to find the list of folders.

2022-09-26 16:06 UTC, mnm678 commented on tap14.md
> +The repository may also maintain a `supported-versions.json` file so that the client
I was thinking the metadata directory

2022-09-26 16:09 UTC, mnm678 commented on tap14.md
> +directories. In addition, repositories SHOULD maintain a `supported-versions.json` file
Yeah, I was trying to sign post what's in this section, but it does repeat the info from above. I can remove here if you think it isn't needed.

2022-09-26 18:04 UTC, trishankatdatadog commented
> @trishankatdatadog I think that's _most_ repositories. For instance, go-tuf _only_ has built-in support for HTTP remotes, and IIRC python-tuf is the same, but HTTP doesn't have a (standard/uniform) way to list the contents of a directory. We ran into this when attempting to build out TAP-14 support in python-tuf.

I see, I understand this better now, thanks.

Why Not Just ™️ use a convention to create and find the supported versions? For example, TAP 14 could mandate that metadata for each major spec version should go into its own directory (e.g., `1`, `2`, `3`...). Then, similar to the way we use [the N+1 rule](https://theupdateframework.github.io/specification/v1.0.31/index.html#update-root) to try to find the next root metadata, a client could also use the N+1 rule to try to find the latest supported major version. WDYT?

2022-09-27 14:48 UTC, joshuagl commented
> > @trishankatdatadog I think that's _most_ repositories. For instance, go-tuf _only_ has built-in support for HTTP remotes, and IIRC python-tuf is the same, but HTTP doesn't have a (standard/uniform) way to list the contents of a directory. We ran into this when attempting to build out TAP-14 support in python-tuf.
> 
> I see, I understand this better now, thanks.
> 
> Why Not Just ™️ use a convention to create and find the supported versions? For example, TAP 14 could mandate that metadata for each major spec version should go into its own directory (e.g., `1`, `2`, `3`...). Then, similar to the way we use [the N+1 rule](https://theupdateframework.github.io/specification/v1.0.31/index.html#update-root) to try to find the next root metadata, a client could also use the N+1 rule to try to find the latest supported major version. WDYT?

I'd guess because we want the spec to move away from assuming a filesystem to describe the API. That is, it should be possible to implement TUF without a filesystem even if today that requires interpreting rather than implementing certain portions of the spec.

2022-09-27 17:35 UTC, trishankatdatadog commented
> I'd guess because we want the spec to move away from assuming a filesystem to describe the API. That is, it should be possible to implement TUF without a filesystem even if today that requires interpreting rather than implementing certain portions of the spec.

I don't see why the try-and-see heuristic requires a filesystem tho?

2022-09-28 17:44 UTC, trishankatdatadog commented
> It's mostly because you can't actually fetch a directory in http, you have to try to fetch a file within the directory, so you have to know the name of the file. If a spec change changed the name of `root.json` or something, we couldn't rely on the existence of any particular file within the directory.

Could you please explain the use case for listing "files" in a "directory"? I'm still missing why this is needed.

2022-09-28 17:58 UTC, znewman01 commented
TAP-14 puts different major-versioned metadata in directories like `2/` and `3/`. Clients are supposed to figure out what the latest supported major version is. In a filesystem, this is easy: `ls /repo/metadata/` and look for the directories.

Over HTTP, I can't `GET /repo/metadata/` (or rather I can, but what it gives me is totally server-dependent and may not include the list of contained files.

The next thing you might try is `GET /repo/metadata/2/root.json` etc.

There's three issues:

1. A major version change *may not* actually require a new `root.json`. (We could make this a requirement, but it's not in the TAP).
2. `root.json` in the next major version might be `root.yaml` or something. We want to be able to tell if there's a major version *beyond* the latest one supported in this client, so we can issue a warning (that's part of the existing TAP-14 spec).
3.  You may in fact have a repo that *skips* major versions: it might have been published under v1, and didn't get around to an upgrade until v3. So the N+1 trick doesn't work. (We could *require* in the TAP that you never skip major versions, but as-written you can't).

Beyond that, the implementation is pretty annoying. The supported-versions file is just a hint. You could make it a `.txt` file with 1 directory per line, but the fact that v1 is in the root complicates that a little bit, so we decided to be more specific and clear in the data format.

2022-09-28 18:44 UTC, trishankatdatadog commented
> Beyond that, the implementation is pretty annoying. The supported-versions file is just a hint. You could make it a `.txt` file with 1 directory per line, but the fact that v1 is in the root complicates that a little bit, so we decided to be more specific and clear in the data format.

I see, that's very helpful, thanks! I'm just slightly worried about the relative complexity this adds while providing relatively little benefit. I'm not convinced that there is a use case where clients will want to choose which major version they want to support. It would certainly be a very complicated client, and I can't imagine a high demand for such a feature. My guess is that people will simply use different clients for different major metadata versions of the same repo.

So, sorry, I'm not trying to be difficult here, but I think we can punt this feature to the future, if it's ever needed. WDYT?

2022-09-28 21:01 UTC, znewman01 commented
>  I'm just slightly worried about the relative complexity this adds while providing relatively little benefit. I'm not convinced that there is a use case where clients will want to choose which major version they want to support. It would certainly be a very complicated client, and I can't imagine a high demand for such a feature. My guess is that people will simply use different clients for different major metadata versions of the same repo.
>
> So, sorry, I'm not trying to be difficult here, but I think we can punt this feature to the future, if it's ever needed. WDYT?

This seems like an argument against TAP 14 more generally, rather than this change in particular, right?

If anything, this change makes the client-side implementation substantially easier. It shouldn't be particularly hard on the repo side either.

2022-09-28 21:23 UTC, mnm678 commented
> I see, that's very helpful, thanks! I'm just slightly worried about the relative complexity this adds while providing relatively little benefit. I'm not convinced that there is a use case where clients will want to choose which major version they want to support. It would certainly be a very complicated client, and I can't imagine a high demand for such a feature. My guess is that people will simply use different clients for different major metadata versions of the same repo.
> 
> So, sorry, I'm not trying to be difficult here, but I think we can punt this feature to the future, if it's ever needed. WDYT?

The proposal here is very similar to using a different client for different major versions, but the TAP 14 checks provide a way for clients to make the decision about which of these versions to use when potentially interacting with multiple repositories. The TUF spec has to account for all types of TUF implementations, including repos with multiple clients, clients with multiple repos, and combinations thereof, which is why this TAP was designed to cover all of these cases.

Implementations could choose to only list a single supported version at a time as either a client or repo, and that will limit their implementation to that particular version.

The reason we need this now-ish is to support future compatibility with breaking changes (like DSSE). The sooner we solve breaking changes the sooner we can move forward with a bunch of other TAPs that require some amount of non-backwards compatibility, without breaking things for our many exisiting users.

2022-09-30 14:32 UTC, trishankatdatadog commented
I see, thanks for the explanation, Zach and Marina! Ok, now I'm convinced that we do need the contents of `supported-versions.json` somewhere. However, I'm not convinced that we need it as a separate file, which raises tricky questions such as who signs it, does it expire, etc. If it's expected to be signed by the root role, why not just stick it in there as an optional field in every root metadata for a major spec version? A little redundant, but simplifies life overall in my opinion. WDYT?

2022-09-30 15:28 UTC, trishankatdatadog commented
> I don't think it's expected to be signed by the root role. Don't think of it as a metadata file, think of it as a hint.

SGTM. Now the Q is: do we sign or not sign this hint?

2022-09-30 15:55 UTC, JustinCappos commented
FYI all, @Marina Moore ***@***.***> and I had a nice chat about this
issue and laid out the pros and cons.

She's going to capture this in writing here so we have it for posterity.
Let's wait for her analysis and then discuss further.

On Fri, Sep 30, 2022 at 11:28 AM Trishank Karthik Kuppusamy <
***@***.***> wrote:

> I don't think it's expected to be signed by the root role. Don't think of
> it as a metadata file, think of it as a hint.
>
> SGTM. Now the Q is: do we sign or not sign this hint?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/theupdateframework/taps/pull/158#issuecomment-1263718194>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAGROD4FIH4DAUUCTDKKRRLWA4BJJANCNFSM54W2DCEQ>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-09-30 19:39 UTC, mnm678 commented
Can we get consensus on this approach from TAP maintainers? @JustinCappos and @trishankatdatadog have already looked. @lukpueh and @joshuagl wdyt?

2022-10-03 09:54 UTC, joshuagl submitted a review, later dismissed
Adding a field to root metadata feels like a more appropriate path forwards. 👍

2022-10-03 09:54 UTC, joshuagl commented on tap14.md
> +freeze attacks, root metadata SHOULD include a `supported-versions` field that lists
Observation, this feels like it will be a good place to provide additional guidance for repository operators on managing "supported" versions.

2022-10-05 12:21 UTC, lukpueh commented
Unrelated observation [about this paragraph](https://github.com/theupdateframework/taps/blame/0b27e8849c1c4bb5095ba16d68e8b1db5ed2c7c5/tap14.md#L192-L194):
> For example, during the course of an update a client could use 4.0.0_parse_root, 4.0.0_parse_snapshot, 4.0.0_parse_timestamp, 4.0.0_parse_targets, 4.0.0_parse_delegation, and 3.0.0_parse_delegation.

If the order of function calls should represent the course of an update, `*_parse_timestamp` should be before `*_parse_snapshot`.

2022-10-05 12:26 UTC, lukpueh commented
Unrelated observation [about this paragraph](https://github.com/theupdateframework/taps/blame/0b27e8849c1c4bb5095ba16d68e8b1db5ed2c7c5/tap14.md#L227-L228):

> If the change adds a new feature that is backwards compatible, for example in TAP 4 and TAP 10 [...]

TAP 10 [claims](https://github.com/theupdateframework/taps/blob/master/tap10.md#backwards-compatibility) that it is backwards incompatible.

2022-10-05 12:36 UTC, lukpueh commented
Ping https://github.com/theupdateframework/taps/pull/158#issuecomment-1203886869, cc @mnm678

2022-10-05 13:56 UTC, lukpueh commented on tap14.md
> +5.root.json first in 3, then 2, then 1. If this file is found, the
This process requires a `VERSION.root.json` filename convention, but in discussion [above](https://github.com/theupdateframework/taps/pull/158#issuecomment-1261277925) and in the [google doc](https://docs.google.com/document/d/1QcjEKzL0dHMVDmpkeIZuNIkN6VzduKBHa-4Mw-XSSx4/edit?usp=sharing) suggest that root may change its filename anytime.

2022-10-05 14:16 UTC, lukpueh commented on tap14.md
> +`supported-versions` field in root metadata.
I'm trying to wrap my head around the upgrade+update process. Would someone be willing to walk me through an extremely simple example for the following scenario:
- repo has 1.root.json with supported version 2
- client has same 1.root.json as trusted root, and client library supports versions 2 and 3
- repo upgrades to spec version 3 and updates root to version 2
- client upgrades+updates root using the `supported_versions` field

Questions:
- Which files need to be created in the repo during the upgrade/update and which keys are used to sign them?
- Which files are downloaded by the client and in what order?

2022-10-06 14:56 UTC, lukpueh submitted a review, later dismissed
Following a chat with @mnm678 and @JustinCappos, I just pushed a couple of minimal fixes for the concerns I raised. @joshuagl, can you green-light again?

2022-10-06 15:50 UTC, JustinCappos commented on tap14.md
> +`supported-versions` field in root metadata.
Glad to have the chat.  Let's make sure this is clarified in writing for posterity too...

2022-10-06 16:33 UTC, trishankatdatadog commented on tap14.md
> +looking for the directory with the largest version number, or by parsing the
WDYM "looking for the..."? Do you mean guess-and-try?

2022-10-06 19:04 UTC, abs007 commented on tap14.md
>  1.0.0 and the highest supported version is 3.0.0, the client will look for
Should it be explicitly mentioned in the example that the min supported major version is 1 because it might be confusing to interpret that. In this case it makes sense since 1 is the first version by default but someone might not be able to figure that out in their first read. What do you think?

2022-10-07 00:29 UTC, JustinCappos commented on tap14.md
>  1.0.0 and the highest supported version is 3.0.0, the client will look for
I'd like to second this.  We should be explicit that TUF 1.0 is /1/, and that the major version number of the specification will be the directory number (2.0 -> /2/, 3.0 -> /3/, etc.) moving forward.

2022-10-07 10:10 UTC, joshuagl commented on tap14.md
> +looking for the directory with the largest version number, or by parsing the
Rather than have a client always try to do the "look for version=N+1", wouldn't it make more sense for the TAP to suggest _only_ using the `supported_versions` field from the root metadata?

2022-10-07 19:18 UTC, mnm678 commented
Based on discussion with @JustinCappos and @lukpueh I simplified the root metadata update mechanism in this TAP. The new mechanism allows the root version numbers to diverge between specification versions without compromising the security of an upgrade. I will update the PoC shortly to reflect this change.

2022-10-11 18:56 UTC, JustinCappos approved these changes
Thanks for the hash / supported_versions change to the text.  Looks ready to me.

2022-10-11 22:07 UTC, trishankatdatadog approved these changes
LGTM to merge as draft for now, please do address my comments as we discussed earlier:
* The unclear benefits of `becomes_obsolete` at the expense of added complexity (e.g., delegatees could accidentally create conflicts)
* If we keep `becomes_obsolete`, clarify whether it uses the same datetime format as `expires`
* Clarify that root rotation is done as before this TAP for the current known MAJOR spec version before looking at (the latest) `supported_versions`
* Clarify whether a root metadata file refer to MAJOR versions lower than or equal to the current `spec_version` in that file (and metadata version directory)
* There are only 3 cases for checking version numbers: <, =, or >. The current text is ambiguous about the < case. Please clarify.

2022-10-11 22:26 UTC, merged