Move Tap14 to accepted with some additional clarification of repository operations
theupdateframework/taps pull request #162
Opened 2022-10-04 15:43 UTC by mnm678

Requires #158

Please ignore all but the last 2 commits, this is already rebased onto #158 to prevent conflicts. I'll clean up the history here once that is merged.

This pr adds some requested clarification of repository operations, and proposes moving this TAP to accepted based on the PoC in python-tuf.

2022-10-06 15:51 UTC, JustinCappos requested changes
FYI: the main index of TAPs also needs to be updated to change the status to accepted...

2022-10-11 18:50 UTC, JustinCappos submitted a review, later dismissed

2022-10-12 10:06 UTC, lukpueh requested changes
Some comments, which I think should be addressed before accepting the TAP

- This PR has conflicts.

- The TAP does not point to a prototype implementation, and the existing prototype implementation (https://github.com/theupdateframework/python-tuf/pull/2114) does not represent the current state of the TAP yet.

- The recently merged PR [#158](https://github.com/theupdateframework/taps/pull/158) had a few spelling mistakes and typos in the last commit (e.g. `supported-versions` with dash instead of underscore)

- The `supported_versions.path` field seems to be redundant with the convention that spec version `X.Y.Z`  metadata lives in an `X` directory.

- How does `root-filename` evolve over root versions? E.g. `2/2.root.json` and `2/20.root.json` can't both say `{"version": 3, "root-filename": "1.root.json", ...}`, because `3/1.root.json` needs to be signed by *"the root key from the most recent metadata [at the time of creating the new root (??)] in the previous major specification version"* and keys may have changed between `2/2.root.json` and `2/20.root.json`. 

  Does this mean that root updates need to be synchronized across multiple versions and `root-filename` needs to be bumped on each root update? IMO that seems necessary for clients, in order to update spec version coming from different root versions. But it also makes the different spec versions less autonomous. Either way I think the TAP should clarify this in the "repository updates" section.

  Besides, how does `root-filename` evolve for the own and previous versions? E.g. if a repo supports spec versions 2, 3 and 4, what would the `supported_versions` entries for 2 and 3 likely look like in `3/8.root.json`?

- I'd generally like the client update process to be more algorithmic also with regards to the existing client workflow. E.g. @trishankatdatadog [suggests](https://github.com/theupdateframework/taps/pull/158#pullrequestreview-1138209759) that the client should rotate root before looking at `supported_versions`. Is that the case? The TAP does not make that clear.

2022-10-20 15:26 UTC, mnm678 commented
@lukpueh I addressed your text concerns, and will be updating the prototype implementation soon. Hopefully the implementation will further clarify the root update process.

2022-10-31 15:28 UTC, mnm678 commented
The implementation now reflects the changes in this TAP. @lukpueh @JustinCappos this is ready for review

2023-09-14 00:09 UTC, JustinCappos requested changes
I looked and the recent changes are fine with me.  (Modulo a minor edit below.)

2023-09-14 00:09 UTC, JustinCappos commented on tap14.md
> +For additional optimizations, the repository could any duplicate metadata files
grammar error here in reference to 'any'

2023-11-06 21:36 UTC, JustinCappos submitted a review, later dismissed
I approve

2024-03-19 11:27 UTC, jkjell approved these changes

2024-03-19 11:28 UTC, JustinCappos approved these changes
Moving to deferred.  Lukas and others will add other changes.

2024-03-19 11:29 UTC, lukpueh approved these changes

2024-03-19 11:30 UTC, merged