Update use cases
theupdateframework/taps pull request #172
Opened 2023-02-28 19:29 UTC by mnm678

Add use cases for community repositories and Fulcio, per [discussion on GitHub](https://github.com/theupdateframework/taps/issues/37#issuecomment-1441192398) and update the section on timestamp and snapshot rotation per #170

2023-02-28 20:21 UTC, trishankatdatadog approved these changes

2023-02-28 20:23 UTC, trishankatdatadog commented
LGTM, but cc @jku based on his recent [comments](https://github.com/theupdateframework/taps/issues/37#issuecomment-1446211360)

2023-09-12 19:00 UTC, mnm678 commented
@JustinCappos @joshuagl Can I get another review on this?

2023-09-13 23:57 UTC, JustinCappos requested changes

2023-09-13 23:57 UTC, JustinCappos commented on tap8.md
> +TAP 18 proposes the use of Sigstore's Fulcio to replace long-lived keys with short-lived keys backed by OIDC identities. This use of identities rather than keys simplifies key management for signers
Can you line wrap this as is the case in the rest of the doc?

2023-09-13 23:57 UTC, JustinCappos commented on tap8.md
> +Timestamp and snapshot keys cannot rotate using this mechanism. Rotate files are included in snapshot metadata, and so cannot be used by timestamp and snapshot, which must be verified before the use
Some rationale why may be useful  

Even indicating why this change was made would help us to preserve a historical record.

For other readers, TAPs and academic papers should clearly explain the reasons why.  However, the specification itself can focus instead on "what"

2023-09-14 08:44 UTC, joshuagl reviewed
Looks good with Justin's suggestions.

2023-09-14 08:44 UTC, joshuagl commented on tap8.md
> +TAP 18 proposes the use of Sigstore's Fulcio to replace long-lived keys with short-lived keys backed by OIDC identities. This use of identities rather than keys simplifies key management for signers
```suggestion
TAP 18 proposes the use of Sigstore's Fulcio to replace long-lived keys with short-lived keys backed by OIDC identities. This use of identities rather than keys simplifies key management for signers in TUF, but it presents an issue when teams that manage a targets metadata file change over time. In TUF today, if a team member leaves, they can pass on a key for use by another team member until the delegating targets metadata is able to update the delegation to a new team member. However, OIDC identities are generally tied to email accounts and other personal data, and so cannot be shared even for the short term. To address this, teams need a way to indicate that a different OIDC identity should be used without waiting for interaction from the delegating metadata.
```

2023-09-18 12:22 UTC, joshuagl approved these changes

2024-01-17 22:22 UTC, JustinCappos approved these changes

2024-01-17 22:22 UTC, merged